nrc-cnrc/EGSnrc

- HEN_HOUSE/egs++/view/image_window.cpp
See PR #16.
This change fixes a porting regression where on interacting with the image window 
it would black out for the duration of the interaction. It also protects against a possible
bug in which the scene could render before a geometry is set.
> Fix egs_view thread porting regression where simple scenes black out

- HEN_HOUSE/egs++/egs_shapes.h
Take into account midpoint of cylinder when sampling within the shape.
> Fix sampling of point within cylinder shape

- HEN_HOUSE/scripts/egsnrc_cshrc_additions
Variable expansion with a colon after it treats the letters after the colon as modifiers. Wrap the variable in curly braces to avoid a bad modifier error.
> Fix bug in cshrc additions script

- HEN_HOUSE/egs++/egs_advanced_application.cpp
This PR just fixes a couple of out-of-order initialization warnings as well as eliminating an unused variable warning for tsave in egsHowFar (since it's only used in the GDEBUG block).
> Fix some egs_advanced_application.cpp compiler warnings

- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.cpp
- HEN_HOUSE/egs++/sources/egs_isotropic_source/egs_isotropic_source.cpp
- HEN_HOUSE/omega/progs/gui/beamnrc/pegsless_egsnrc.tcl
Without the initializer the destructor will access an uninitialized `nrs` variable at line 138 in egs_isotropic_source.h
> Add missing nrs initializer to egs_isotropic_source constructor

- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.cpp
- HEN_HOUSE/egs++/sources/egs_isotropic_source/egs_isotropic_source.cpp
- HEN_HOUSE/egs++/sources/egs_isotropic_source/egs_isotropic_source.h
- HEN_HOUSE/omega/progs/gui/beamnrc/pegsless_egsnrc.tcl
egs_isotropic_source gives warnings when a source is created or destructed. No other source (as far as I can tell) outputs such warnings. I suggest removing them.
> Remove unnecessary warnings in egs_isotropic_source

- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.cpp
- HEN_HOUSE/egs++/egs_run_control.cpp
- HEN_HOUSE/omega/progs/gui/beamnrc/pegsless_egsnrc.tcl
A space is missing between the cpu time in hours and its units.
> Add space between value and units in output

- HEN_HOUSE/egs++/egs_alias_table.h
Unmatched #ifndef / #define header guard pair generates warning on some compilers.
> Fix egs_alias_table header guard

- HEN_HOUSE/user_codes/tutor7pp/tutor7pp.cpp
Events depositing the maximum particle's energy are not scored in the histogram. As a consequence, large differences are observed in those cases if one compares the energy deposited in a given region calculated from the fraction of energy deposited to the sum over all histogram bins. Now when Emax is deposited in a region, it is scored in the last bin.
> Fix pulse height scoring in tutor7pp

- HEN_HOUSE/scripts/egs-backup-github
Uses curl with the GitHub API to create local copies of the GitHub issues and pulls in json format. Also creates bare git clones of the EGSnrc repository and wiki. Backups can be created regularly by running this script with cron.
> Add script to create EGSnrc github backups

- HEN_HOUSE/egs++/view/egs_visualizer.cpp
- HEN_HOUSE/egs++/view/image_window.cpp
- HEN_HOUSE/egs++/view/renderworker.cpp
- HEN_HOUSE/egs++/view/renderworker.h
- HEN_HOUSE/egs++/view/viewcontrol.cpp
- HEN_HOUSE/egs++/view/viewcontrol.h
Previously, when the image window was resized, the field of view did not change so that the the visible scene would be distorted. Now elongating the image window increases the size of the field of view accordingly to avoid distortion.
Left: Render at 512x1024, before this change; right: render at 512x1024, after this change.
> egs_view no longer stretches objects for nonsquare image window

- HEN_HOUSE/egs++/egs_spectra.cpp
Following the proposed solution in issue #74 here is the actual fix:
- Introduced input key `spectrum mode` for intrinsic definition of a
tabulated spectrum which has the same meaning as the `mode` flag 
in `EGSnrc` spectrum files.
- The input key `spectrum type` is still valid although considered
_deprecated_ from now on.
- Type 3 in EGS_AliasTable has been left untouched, although it 
does _exactly_ the same as type 2. This avoids breaking any
user implementation relying on the existence of type 3.
- Although the documentation was already pointing at an equivalence 
between the `mode` of spectrum files and the `type` of intrinsically 
defined spectra, an update is required to reflect the use of `spectrum mode`
rather than `spectrum type`
> Fix issue #74 (tabulated spectrum)

- HEN_HOUSE/gui/egs_inprz/include/tooltips.h
- HEN_HOUSE/gui/egs_inprz/src/inputRZForm.cpp
- HEN_HOUSE/gui/egs_inprz/src/inputRZImpl.cpp
- HEN_HOUSE/gui/egs_inprz/src/pegslessinputs.cpp
- HEN_HOUSE/gui/egs_inprz/ui/inputRZ.ui
Fixes included:
1. Elimination of segmentation fault when browsing density
correction files in pegless media def.
2. Truncation of float values to int when saving no. of
atoms in pegsless media def.
3. Proper enabling of energy table when dosrznrc .egsinp file
specifies a pulse height distribution calculation
4. Ability to browse from EGS_HOME and HEN_HOUSE for
density correction files in pegsless media def.
> Fix various issues with egs_inprz

- HEN_HOUSE/gui/egs_inprz/src/inputRZImpl.cpp
If the directory `$EGS_HOME/pegs4/density_corrections` is not found then the search begins in `$EGS_HOME/pegs4`.
> Fix density correction path starting in EGS_HOME

- HEN_HOUSE/gui/egs_gui/pegs_page.cpp
- HEN_HOUSE/gui/egs_gui/pegs_page.h
- HEN_HOUSE/gui/egs_gui/pegs_runoutput.cpp
- HEN_HOUSE/pegs4/pegs4.mortran
- HEN_HOUSE/src/get_media_inputs.mortran
Consistent search paths and order for density correction files between
pegs4 and codes running in pegsless mode.  Also, changed egs_gui so
that it always calls pegs4 with full density correction file name.
Finally, changed egs_gui so that, on executing pegs4, if the density
correction file is not found, an error dialog pops up.  Order of
search for density correction file is:
1. full pathname
2. $EGS_HOME/pegs4/density_corrections/
3. $EGS_HOME/pegs4/density_corrections/elements
4. $EGS_HOME/pegs4/density_corrections/compounds
[5. $EGS_HOME/pegs4/density/ -- for pegsless to preserve compatibility
with past installations where this directory was created]
5[6]. $HEN_HOUSE/pegs4/density_corrections/elements
6[7]. $HEN_HOUSE/pegs4/density_corrections/compounds
> Fix 67: Fix inconsistent search paths for density correction file.

- HEN_HOUSE/egs++/egs_transformations.h
The description of the 'rotation vector' input of affine transforms
specifies that it "defines a rotation which, when applied to the 3D
vector defined by the input, transforms it into a vector along the
positive z-axis". Thus, it's natural to input:
'rotation vector = 0, 0, -1'
in order to flip an object 180 degrees along the z-axis (i.e., by
rotating 180 degrees around the x-axis or around the y-axis.)
This commit defines a rotation of 180 degrees around the x-axis when
a vector pointing along the negative z-axis is input as the 'rotation
vector'.
> Allow negative z-axis vector as a rotation vector

- HEN_HOUSE/egs++/geometry/egs_cd_geometry/egs_cd_geometry.h
Two cases are mishandled by the howfar method:
1) A particle is approaching the geometry, but due to round off, ends
up sitting exactly on the boundary. At that point, it will be considered
inside the CD geometry which causes a mismatch with its global region
number. The problem is that the check for condition (b) in the code
fails to catch this case. When the particle sits on the boundary, the
howfar call will set 'tb' to the distance to the next boundary, which
can be much larger than 'epsilon' (and it can also return ixnew < 0
if there is no other CD geometry region along the direction of 'u' 
between the particle and the outside of the CD geometry.) Solution:
call howfar, but in the opposite direction, which should set 'tb' to 0 if
sitting on the boundary.
2) A particle has just left …
> Improve CD geometry's howfar

- HEN_HOUSE/egs++/geometry/egs_cd_geometry/egs_cd_geometry.h
Tabs introduced in commit f1a69ffd9c4854ab44203506056bf44d9b4de33d were misaligning the code.
> Fix tabs and format

- HEN_HOUSE/egs++/geometry/egs_cones/egs_cones.cpp
Conestacks with multiple layers whose outer radii are different are concave geometries. To reduce geometry errors when conestacks are inscribed in CD geometries, the is_convex flag should be explicitly set to 'false' when appropriate.
Along with pull request #87, this fixes all non-overlapping cases of issues #28 and #31. The issue was not a particle near a corner, as an inspection in egs_view revealed. Instead, when a particle exited, then re-entered the conestack in one step, errors were prone to occur. See screenshot below, along with a screenshot after the fixes (this one and #87) are applied.
> Set is_convex to false for concave conestacks

- HEN_HOUSE/egs++/geometry/egs_cones/egs_cones.cpp
- HEN_HOUSE/egs++/geometry/egs_cones/egs_cones.h
This patch resolves a number of compiler warnings for the egs_cones
geometry.  Most importantly is the change in EGS_ConeSet::hownear to
properly initialize the tc variable. If hownear is called with ireg=0 or
ireg=2*nc then `tc` never gets set and the tco < tc comparison in the
last line of the function will produce undetermined results.
> Fix uninitialized values/compiler errors in cones

- HEN_HOUSE/egs++/geometry/egs_cones/egs_cones.h
Due to floating point errors, the distance to the exit plane of a simple cone can be negative when the particle is: 1) inside the cone; 2) sitting on the exit plane; 3) and leaving the geometry. This leads to endless loops in the howfar of CD geometry, under certain circumstances.
> Prevent negative distance to exit plane in simple cone

- HEN_HOUSE/scripts/run_user_code
Single jobs can now be run in pegsless mode with:
`ex user_code inputfile pegsless`
> Support pegsless run in run_user_code

- HEN_HOUSE/egs++/shapes/egs_polygon_shape/egs_polygon_shape.cpp
- HEN_HOUSE/egs++/shapes/egs_polygon_shape/egs_polygon_shape.h
The number of triangles required to span a regular polygon defined by N points is N-2 not N-3 so not enought memory was being allocated.  This has been corrected and resolves #115.
The destructor was also trying to delete N triangles rather than N - 2 which resolves #114
> Fix egs_polygon_shape number of triangle bugs

- HEN_HOUSE/egs++/view/viewcontrol.cpp
- HEN_HOUSE/egs++/view/viewcontrol.h
This changeset adjusts the camera zooming behavior of egs_view. Zooming
is now logarithmic, so that each constant change in zoom input (scrollwheel, etc.)
scales the field of view up or down by the same factor, no matter the current zoom
level. (The exception is an outer bound on the zoom level set to the point where the
FOV is ~60 times wider than the target geometry.) The initial zoom level is still within
a percent or so of the previous initial zoom level.
The zoom rate (i.e., how much a pixel shift with the middle mouse button changes the
FOV width) has been arbitrarily set to `2^(1/48)=1.0145`. This is a middle ground
between the slowest prior zoom rate (`1.0060`) and the fastest (`2.5` [although
occasionally `7.0` happens]).
(Why `2^(1/48)`? Then 24 pixels of change yield an exact …
> Uniform zooming in egs_view

- HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.cpp
This commit adjusts range-based medium selection for `EGS_NDGeometry` to follow the same conventions as for `EGS_XYZGeometry`. Before, a range based selector like
set medium = 0 1 0 1 2 3 4 4 123
would do nothing (since `istart=iend` for the fourth dimension); and changing the last 4 to a 5 would apply medium 123 to two regions. There were a few additional oddities in 3+ dimensions. Now,
set medium = 0 0 0 0 2 2 4 4 123
applies medium 123 to exactly the region with coordinates (0,0,2,4).
None of the `egs++/geometry/example` geometries use this range selection, and it seems rare enough that this commit shouldn't change too many geometries out there.
> Fix range-based medium selection in EGS_NDGeometry

- HEN_HOUSE/omega/progs/gui/beamnrc/set_main_inputs_egsnrc.tcl
Previously, when attempting to turn BCSE on using the GUI, the
GUI crashed with a
"can't read "options(14,3)": no such element in array"
error.  This is because options(14,3) doesn't exist.  Changed
to options(14,2), or DBS, to reflect the comparison that
actually should be made.
> Fix bug in BCSE option with beam_gui

- HEN_HOUSE/doc/src/pirs701-egsnrc/inputs/transport_parameters.tex
- HEN_HOUSE/doc/src/pirs702-egsnrc-codes/inputs/transport_parameters.tex
@mchamberland pointed out that the pirs701 file `transport_parameters.tex` had not been updated to reflect the change of the Bound Compton scattering default value to `norej`. Update the file in this regard, and update a couple of other bits according the pirs702 version of `transport_parameters.tex`.
> Fix #8: update transport parameter description

- HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
Re-ordered variables in common block score largest to smallest.
> Fix #130: DOSXYZnrc compilation warnings

- HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.mortran
- HEN_HOUSE/utils/iaea_phsp_macros.mortran
Supersedes previous fix for this issue, which I've deleted from the pull requests.
> Fix synchronization of DOSXYZnrc source 20 with IAEA phsp sources

- HEN_HOUSE/src/nrcaux.mortran
Fixed SUBROUTINE WATCH so that fluorescent photons resulting from EII
processes after Moller do not get listed as "Resulting electrons"
with negative energies when IWATCH is being used.  Note: This is
an output bug only; it does not affect results!
> Fix #101: Fix negative energies output after Moller

- HEN_HOUSE/src/get_media_inputs.mortran
Change the elements to be automatically changed to upper case for pegsless input. This fixes a crash that occurs when the elements are not found due to the case mismatch.
For example, now you can use the following input:
```
:start glass:
elements = O, Na, Si, Ca
...
```
where previously you were required to use:
```
:start glass:
elements = O, NA, SI, CA
...
```
> Fix pegsless elements lowercase input

- HEN_HOUSE/omega/beamnrc/CMs/PYRAMIDS_cm.mortran
Trivial change, really. The number of local regions is 3 times the number of pyramid blocks since the inner and outer air regions are actually the same numbered region. Change is to the comment only, for clarity.
> Fix typo in comment in PYRAMIDS_cm

- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.cpp
- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.h
- HEN_HOUSE/egs++/egs_application.h
- HEN_HOUSE/egs++/egs_base_geometry.cpp
- HEN_HOUSE/egs++/egs_base_geometry.h
- HEN_HOUSE/user_codes/egs_chamber/egs_chamber.cpp
Addresses issue #139.
Now you can set labels in geometries in egs_chamber using `set label` within the geometry block. For example:
```
:start geometry:
...
set label = myLabel 3 4 5
:stop geometry:
```
This assigns the local geometry regions 3 4 5 to the label named myLabel. Cavity regions, enhance regions and subgeom regions can then use myLabel in place of the global region numbers. Multiple labels, and mixed global region numbers with labels are both supported.
```
:start scoring options:
:start calculation geometry:
geometry name = myGeom
cavity regions = detectorLabel
cavity geometry = myGeom
enhance regions = enhanceLabel
enhancement = -128
cavity mass = ...
:stop calculation geometry:
:stop scoring options:
```
I also added this to `egs_dose_scoring`, so you can use region labels …
> Add region labels to egs_chamber and egs_dose_scoring

- HEN_HOUSE/scripts/compile_user_code
Remove back quotes from the usage message, which were interpreted as
command substitution by the shell and caused the script to fail. Also
update the usage message and fix a couple typos.
> Fix #167: Unmatched quotes in compilation script

- HEN_HOUSE/scripts/run_user_code_batch
Go to the application directory before invoking PBS distributed shell
(pbsdsh) parallel runs, so that they can be launched from any location,
in particular from the home directory when submitting jobs remotely via
ssh.
> Go to application directory for pbsdsh batch mode

- HEN_HOUSE/omega/progs/gui/dosxyznrc/load_input2_nrc.tcl
- HEN_HOUSE/omega/progs/gui/dosxyznrc/reset_parameters_nrc.tcl
1. Error caused by variable, the_vcu_code, not defined
2. Typo: "imusphspout" instead of "imuphspout"
> Fix #175: Fix two bugs in dosxyz_gui

- HEN_HOUSE/omega/beamnrc/beamnrc.mortran
Warnings were ultimately traced to cases where source particles
were recycled, in which case, unless an angled phase space source
(source no. 24) was used or Z was scored in the phase space
files (IZSCORE=1), the CM on which particles were incident was
not saved in variable INIT_ICMOLD.  The next time the particle
was used, INIT_ICM was set to a nonsense value.
The fix simply involved unconditionally saving INIT_ICM in
INIT_ICMOLD when particles are recycled.
Unsure why this bug has not appeared before.
> Fix #90: Fix -ve ustep warnings with IAEA phsp source

- HEN_HOUSE/utils/phsp_macros.mortran
Segmentation fault was due to the last job's attempt to close
phase space files that had already been closed.  Affected
jobs outputting EGS-format phase space as well, but in this
case no segmentation fault occurred.
> Fix #51: Fix segmentation fault in parallel IAEA phsp output

- HEN_HOUSE/src/get_media_inputs.mortran
Calculated density corrections based on an input value of GASP
(gas pressure) are disabled when a density correction file is used.
Moreover, if both a density correction file and a GASP>0 are specified,
the pegsles implementation crashes if GASP is not unity.  In the fix,
GASP is reset to 0 (i.e. corrections using GASP turned off) if a
density correction file is used.
> Fix issue when GASP>0 and density correction file used.

- HEN_HOUSE/omega/progs/gui/beamdp/browser.tcl
Browser would only show IAEAphsp files if the GUI was
started in the directory containing the files.  Once
you navigated away and back into the directory, these
files were no longer visible.
> Fix beamdp GUI browser bug.

- HEN_HOUSE/omega/progs/addphsp/addphsp.mortran
Bug was caused by addphsp not including the .IAEAphsp extension
when initially searching to see if the output phase space file
already existed.  As a result, it was impossible to add data
to an existing IAEA phsp file.
> Fix #201: Fix bug in addphsp adding to existing IAEA phsp files.

- HEN_HOUSE/pegs4/pegs4.mortran
Fixes `NaNs` in `pegs4` that occur as a result of the `RLC` variable calculating to zero when the `-ffast-math` compilation flag is not used. The fix is similar to Blake's previous `NaN` fix and simply switches the order of operations. It will give the right result with or without the `-ffast-math` flag.
> Fix nans that occur in pegs4 without -ffast-math

- HEN_HOUSE/omega/progs/gui/beamnrc/pegsless_egsnrc.tcl
- HEN_HOUSE/omega/progs/gui/dosxyznrc/load_input2_nrc.tcl
- HEN_HOUSE/omega/progs/gui/dosxyznrc/pegsless_egsnrc.tcl
Disable the ability to specify the medium is a gas if a density correction file is used.  GASP is not
used in this case.
> Fix beam gui gasp input

- HEN_HOUSE/gui/egs_gui/pegs_page.cpp
- HEN_HOUSE/gui/egs_gui/pegs_page.h
- HEN_HOUSE/gui/egs_gui/pegs_page.ui
- HEN_HOUSE/gui/egs_inprz/include/inputRZImpl.h
- HEN_HOUSE/gui/egs_inprz/include/pegslessinputs.h
- HEN_HOUSE/gui/egs_inprz/src/inputRZForm.cpp
- HEN_HOUSE/gui/egs_inprz/src/inputRZImpl.cpp
- HEN_HOUSE/gui/egs_inprz/src/inputRZSave.cpp
- HEN_HOUSE/gui/egs_inprz/src/pegslessinputs.cpp
- HEN_HOUSE/gui/egs_inprz/ui/inputRZ.ui
For egs_gui: Add an input for gas pressure if medium is a gas
For egs_gui and egs_inprz: disable the option to specify that the medium is a gas if a density correction file is used.  GASP is not used in this case.
> Fix egs inprz and egs gui gasp input

- HEN_HOUSE/egs++/geometry/egs_prism/egs_prism.h
Fix a bug resulting in a crash when a closed prism contained the zero point of the axis along which it is closed. For example, an `EGS_PrismX` with `closed = -1 1` would crash. Transformations to this condition, where zero was enclosed, had the same crash.
> Fix #111: EGS_PrismT geometry bug when enclosing zero along closed axis

- HEN_HOUSE/omega/progs/beamdp/beamdp.mortran
- HEN_HOUSE/omega/progs/gui/beamdp/beamdp_gui.tcl
Previously, beamdp_gui only allowed the user to input no.
of particles for which to output parameters.  This did
not reflect inputs actually required by beamdp: the range
of particles for which to list parameters.  Confusion was
exacerbated by the command line description of this input
from beamdp, itself, which also indicated only the no.
of particles for which to output data.  This has been
fixed as well.  Also, fixed a serious bug resulting in
erroneous data output for all options when IAEA phase space
data was analyzed.
> Fix #152: Fix input bug in beamdp/beamdp_gui for option 11.

- HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
Previously, particles that missed the geometry were subtracted
from the total fluence (used to normalize dose) instead of
added.  This bug has been here for years, indicating, hopefully,
how infrequently these sources are used.
> Fix error in fluence for sources 1 and 7

- HEN_HOUSE/doc/src/pirs898-egs++/Doxyfile
Change Doxyfile `FULL_PATH_NAMES = NO` to hide exposed paths. This removes all paths from the file list so the user can't tell where to find the file, but maybe that is OK.
An alternative would be to use `STRIP_FROM_PATH` to get rid of the start of the path, but then we are providing this path in the Doxyfile itself.
> Fix exposed path in pirs898 file list

- HEN_HOUSE/omega/beamnrc/CMs/PYRAMIDS_cm.mortran
Removed a few lines of code for the particle being in the second slab (inside the bars, inner or outer air). If the particle exits that region going backwards (w<0), it stays in the CM, so WHERE_AM_I should not be called yet.
> Fix bug in PYRAMIDS_cm HOWFAR

- HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.macros
- HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.mortran
This pull request adds a flag to the input for isource = 20 in DOSXYZnrc when a shared library is used. If the flag is set to "1", the calibration run that was previously always performed is skipped. To ensure backwards compatibility with old input files, the default value for the flag is 0, and the calibration run will always run if the flag is omitted in the input file.
In the input file, record SC1-20 (according to pirs794) changes from:
```iqin,isource,nset,i_dbs,r_dbs,ssd_dbs,z_dbs,e_split,i_muidx_out``` to ```iqin,isource,nset,i_dbs,r_dbs,ssd_dbs,z_dbs,e_split,i_muidx_out,calflag```
> Add flag to skip the calibration run performed to refine NRCYCL for isource=20 in dosxyz

- HEN_HOUSE/doc/src/pirs701-egsnrc/inputs/chapter2_3.tex
- Expression for gyroradius was using a vector product when it should have been
its magnitude. This fixes issue #128 .
- Fixed small typo in section regarding radiative Compton corrections.
> Fix gyroradius formula in section 2.4.11.iii of PIRS-701

- HEN_HOUSE/omega/progs/gui/dosxyznrc/set_source.tcl
Fixed bugs related to adding/deleting control points.
The most serious bug resulted in inability to specify
points unless at least one point had already been defined
in the .egsinp file read in.
> Fix dosxyz GUI bugs in sources 20, 21

- HEN_HOUSE/interface/egs_interface1.h
- HEN_HOUSE/interface/egs_interface2.h
The new `edep_local` variable from recent kerma/g fixes was not declared in the cpp interface files. This resulted in the wrong dose in cpp applications that used `iarg=4` (tutor2pp).
> Fix edep_local missing from cpp interfaces

- HEN_HOUSE/scripts/egsnrc_bashrc_additions
BUG: In order to set LD_LIBRARY_PATH for pre-compiled egs_view my_machine
was changed to linux-static. This affected the location of the
application in $EGS_HOME.
This commit fixes it.
> Fix bug setting wrong $EGS_HOME/bin/my_machine folder

- HEN_HOUSE/gui/egs_gui/pegs_page.cpp
- HEN_HOUSE/gui/egs_gui/pegs_page.h
Fixed a bug in which, by unchecking and then re-checking the
ICRU density correction box, the user was able to attempt
to run PEGS4 with a density correction but with medium type
specified as "Compound" (and potentially with a different
composition than that specified in the density correction
file).  PEGS4 failed, but this led to frustration.
> Fix #100: Fix egs_gui not working with compound and dc file

- HEN_HOUSE/doc/src/pirs794-dosxyznrc/pirs794-dosxyznrc.tex
- HEN_HOUSE/omega/progs/gui/dosxyznrc/set_source.tcl
- HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.mortran
DOSXYZnrc code, GUI now do not allow input for sources 20, 21
to have fewer than 2 control points.  This has always been the
min. no. of points required for these sources but it was never
enforced elegantly; the code was simply allowed to crash.
This min. is also explicitly stated in the DOSXYZnrc manual.
> Fix #230: Fix min. no. of control points

- HEN_HOUSE/src/egsnrc.mortran
Fix a bug that happens rarely when the random number rnnoss is set to
zero. This results in ustep=tustep=0 but occasionally they are set to
an erroneous value. With electric and magnetic fields this leads to
infinite loops. See issue #179 for more details.
Now, when the random number is less than 1e-30 it is set to 1e-30. 
@victorMalkov, does this fix the problem? Does anyone see a problem with this solution?
Notice a similar solution in FLURZnrc at line 1461:
```
REPLACE {$SELECT-PHOTON-MFP;} WITH
"==========================="
{;$RANDOMSET RNNO35;IF(RNNO35 = 0.0) RNNO35=1.E-30;
IF(IFORCE = 0)["photon interaction forcing option not chosen"
DPMFP=-LOG(RNNO35);
]
ELSE[
```
> Fix #179: electr bug when ustep in single scattering is zero

- HEN_HOUSE/src/rad_compton1.mortran
The recent rest mass changes added the `medium` variable to `COMIN/USEFUL`. This meant that local definitions of `medium` had to be removed, but `rad_compton1.mortran` got missed in the process. This bug fix simply removes the extra declaration of `medium` from a function, fixing a compile error when you added radiative compton corrections to the Makefile.
This should get cherry-picked into master asap.
> Fix #244: a compile error when using rad_compton1 due to medium

- HEN_HOUSE/src/rad_compton1.mortran
Remove the extraneous declaration of variable "medium" in the radc_init
subroutine. The recent rest mass changes added the medium variable to
COMIN/USEFUL (commit 3bff6ed), hence local definitions of medium had to
be removed. But rad_compton1.mortran got missed in this update.
> Fix #244: compile error in rad_compton1.mortran

- HEN_HOUSE/omega/beamnrc/beamnrc.mortran
Fixed a bug in DBS which resulted in no further LATCH
bits being set once z(np) was > the ssd of the splitting
field.  The bug also meant that ZLAST for these particles
was not set.  The fix involved using a GOTO statement
to jump to the BEAMnrc default LATCH (and ZLAST) setting routines
in AUSGAB instead of immediately exiting when z(np) > ssd.
This is probably a rare bug, given that, in general, users
set ssd = the bottom of the accelerator.
> Fix LATCH/ZLAST with DBS when z(np)> ssd

- HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_cm.mortran
- HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_macros.mortran
- HEN_HOUSE/omega/beamnrc/CMs/SYNCJAWS_cm.mortran
- HEN_HOUSE/omega/beamnrc/CMs/SYNCJAWS_macros.mortran
- HEN_HOUSE/omega/beamnrc/CMs/SYNCMLCE_cm.mortran
- HEN_HOUSE/omega/beamnrc/CMs/SYNCMLCE_macros.mortran
- HEN_HOUSE/omega/beamnrc/CMs/SYNCVMLC_cm.mortran
- HEN_HOUSE/omega/beamnrc/CMs/SYNCVMLC_macros.mortran
Increases the `MAXFIELD` parameter for the BEAMnrc `SYNC` component modules to 1024 instead of 256. This will reduce the number of users than need to increase the parameter manually. Also adds a check to make sure that the number of fields read in from a file is less than the maximum.
> Fix #182: Increase beamnrc sync maxfield and add check

- HEN_HOUSE/omega/beamnrc/CMs/BLOCK_cm.mortran
Fixed an error finding shared planes when the shared edge was the last edge of a subregion. This could lead to an infinite loop trying to find an intersection. Also corrected a spelling error and removed unnecessary check of distance on line 527. Error was brought to my attention by Michael Snyder at Wayne State.
> fixed error finding shared planes

- .travis.yml
- HEN_HOUSE/scripts/configure
- HEN_HOUSE/scripts/configure.expect
- HEN_HOUSE/scripts/egsnrc_bashrc_additions
Implement a simple Travis-CI continuous integration script which automatically build and configures EGSnrc on each pull request. In time we can add more sophisticated tests, but as a starting point this will at least catch basic configuration failures. @mainegra I added the make -j12 flag as a default in the configuration script; if you want to add it in the guis as well, add a commit to this branch and I will squash it with mine.
> Implement a simple Travis-CI continuous integration script

- HEN_HOUSE/scripts/egsnrc_bashrc_additions
Define an alias in `$HEN_HOUSE/scripts/egsnrc_bashrc_additions` to run `egs_view` that sets `LD_LIBRARY_PATH` temporarily in a subshell. Fixes issue #254 .
> Fix use of LD_LIBRARY_PATH for egs_view static

- HEN_HOUSE/interface/egs_c_interface1.macros
- HEN_HOUSE/interface/egs_c_interface2.macros
Fix the rest mass initialization for EGSnrc applications that depend on
the C interface. The bug fix in the parent commit moved the declaration
of the rest mass inside the COMIN/USEFUL/ macro. However this in turn
breaks C and C++ EGSnrc applications because the C interface relies on
its own declaration of the COMIN/USEFUL/ macro, which also has to be
updated with the rest mass data statement.
> Fix #260: rest mass not initialized in C interface

- HEN_HOUSE/omega/beamnrc/beamnrc.mortran
- HEN_HOUSE/omega/progs/beamdp/beamdp.mortran
Changed definition of $REAL in beamdp.mortran from real*4 to
real*8.  Also redefined variables NHSTRY and NHSTRY_LAST
as $LONG_INT (integer*8).  This fixed issues with NAN output
when analyzing large phase space files.
Also made the ICASE shower counter in beamnrc.mortran a
$LONG_INT.  For very large numbers of histories, this was
previously becoming a limiting factor.
> Fix #186: Fix beamdp, beamnrc probs with large numbers

- README.md
The lines in the top-level `README.md` file were wrapped, which caused newlines to be inserted in the mardown links `[...]` or between the links and their href `(...)`. Consequently the links were not parsed properly but displayed as text. This will have to be cherry-picked to master as well.
> Fix mardown links in top-level README

- README.md
The lines in the top-level `README.md` file were wrapped, which caused newlines to be inserted in the mardown links `[...]` or between the links and their href `(...)`. Consequently the links were not parsed properly but displayed as text. This will have to be cherry-picked to master as well. Cherry picked from commit 1b7bea330d56672fca6ddb647bdf8e9075fc1552 to fix the default github repository top page.
> Fix markdown links in top-level README

- HEN_HOUSE/egs++/egs_advanced_application.cpp
- HEN_HOUSE/egs++/egs_application.cpp
- HEN_HOUSE/egs++/egs_base_geometry.cpp
- HEN_HOUSE/egs++/egs_base_geometry.h
- HEN_HOUSE/egs++/geometry/egs_cd_geometry/egs_cd_geometry.cpp
- HEN_HOUSE/egs++/geometry/egs_cd_geometry/egs_cd_geometry.h
- HEN_HOUSE/egs++/geometry/egs_cones/egs_cones.cpp
- HEN_HOUSE/egs++/geometry/egs_genvelope/egs_envelope_geometry.cpp
- HEN_HOUSE/egs++/geometry/egs_genvelope/egs_envelope_geometry.h
- HEN_HOUSE/egs++/geometry/egs_gstack/egs_stack_geometry.cpp
- HEN_HOUSE/egs++/geometry/egs_gstack/egs_stack_geometry.h
- HEN_HOUSE/egs++/geometry/egs_gtransformed/egs_gtransformed.cpp
- HEN_HOUSE/egs++/geometry/egs_gtransformed/egs_gtransformed.h
- HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.cpp
- HEN_HOUSE/egs++/geometry/egs_smart_envelope/egs_smart_envelope.cpp
- HEN_HOUSE/egs++/geometry/egs_smart_envelope/egs_smart_envelope.h
- HEN_HOUSE/egs++/geometry/egs_union/egs_union_geometry.cpp
- HEN_HOUSE/egs++/geometry/egs_union/egs_union_geometry.h
- HEN_HOUSE/egs++/sources/egs_fano_source/Makefile
- HEN_HOUSE/egs++/sources/egs_fano_source/egs_fano_source.cpp
- HEN_HOUSE/egs++/sources/egs_fano_source/egs_fano_source.h
- HEN_HOUSE/egs++/sources/egs_isotropic_source/egs_isotropic_source.cpp
- HEN_HOUSE/egs++/sources/egs_isotropic_source/egs_isotropic_source.h
- HEN_HOUSE/interface/egs_c_interface2.macros
- HEN_HOUSE/interface/egs_interface2.h
- HEN_HOUSE/src/egs_utilities.mortran
- HEN_HOUSE/src/egsnrc.macros
- HEN_HOUSE/src/egsnrc.mortran
- HEN_HOUSE/src/emf_macros.mortran
- HEN_HOUSE/src/get_inputs.mortran
The `feature-emf` branch is a cleaned up version of the `emf` branch. It was not trivial to bring this branch up to date with `develop`, because of concurrent modifications in the same files since the `emf` branching point. I checked carefully that all changes related to the Fano source and magnetic field scaling have been preserved, but I need more eyes on this, and test runs.
The Fano source was initially implemented as an option in the isotropic source, but then segregated to a separate source in its own right. I propose to leave the commits as they are and merge into `develop`, to preserve the implementation history. **Once this is merged, the older `emf` branch can be deleted as well.**
I adjusted Authors and Contributors, and fixed a few instances in the new Fano source files that …
> Add Fano source and magnetic field scaling

- HEN_HOUSE/user_codes/cavity/cavity.cpp
Add a check to see if the array Rho has been defined. This avoids a segmentation fault that occurred for non fluence calculations. This bug was introduced in PR #289.
> Fix a bug in cavity for non fluence calculations from PR #289

- HEN_HOUSE/src/egsnrc.mortran
When `$EADL_RELAX = true` and the photon interacts with a shell
below `L3` the photon energy was being deposited locally rather
than emitting a photo-electron with the photon energy. This is
corrected here.
Similarly, when the photon energy falls below the binding energy
`binding_energies($MXSHELL,iZ)`, which for `$EADL_RELAX = true` is the
binding energy of the `M2` shell, one should also emit a photo-electron
rather than deposit the energy on the spot.
> Fix bug in photoelectric routine

- HEN_HOUSE/omega/beamnrc/beamnrc.mortran
In changing ICASE to $LONG_INT (integer*8) in BEAM main,
I neglected to change its local version in subroutine
beam_shower(icase) to $LONG_INT.  This caused compiler
warnings.
> Fix #186: Addendum--eliminate variable type mismatch

- HEN_HOUSE/user_codes/egs_cbct/egs_cbct.cpp
One error message in egs_cbct failed to report the file size correctly because the `EGS_BaseFile` object `bs` was deleted before the `egsFatal` message. Now we save the file size in a variable before deleting the object.
This bug fix was suggested by Felix Thoma.
> Fix a minor egs_cbct bug in an error message

- HEN_HOUSE/user_codes/egs_chamber/egs_chamber.cpp
Fix a bug where radiative splitting was effectively turned off after the first photon interaction with cross-section enchancement. Now nbr_split is set to csplit after RR instead of 1.
> Fix #205: bug in egs_chamber radiative splitting and RR

- HEN_HOUSE/user_codes/edknrc/edknrc.mortran
- HEN_HOUSE/utils/geomsph.mortran
Instead of calling shower, the program uses macro `$DO_PHOTON_SHOWER` which failed to set the value of `GMFPR0` for the initial interaction at the origin. The macro also did not handle cases where initial
energy `EI <= PCUT`, instead allowing `GMFPR0` to be set to 0.  The result of both bugs was many "Infinite" values. These bugs have been fixed. Also fixed a warning in `geomsph.mortran` in which there was an incompatibility in the variable passing `TITLE` to xvgrplot.
> Fix #189: Fix bug in EDKnrc when using photon spectrum with source 0

- HEN_HOUSE/omega/progs/gui/beamnrc/create_accel.tcl
Fix a bug where SYNCHDMLC was not available as an option when creating a new accelerator in the BEAMnrc gui. This was due to the number of CMs being hard-coded in create_accel.tcl. Now the length of the cm_names array is determined correctly.
> Fix #296: SYNCHDMLC not available in BEAMnrc create_accel

- HEN_HOUSE/egs++/egs_ausgab_object.h
- HEN_HOUSE/egs++/egs_base_source.h
- HEN_HOUSE/egs++/egs_ensdf.cpp
- HEN_HOUSE/egs++/egs_ensdf.h
- HEN_HOUSE/egs++/egs_spectra.cpp
Fix compile warnings related to the radionuclide source. The following compile options were used:
`-g -O3 -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare`
> Fix radionuclide source compile warnings

- HEN_HOUSE/scripts/configure
Add a basic compilation test after the Fortran compiler flag selection
in the configure script, to correctly report the issue if the flags
cause a compilation problem. Previously, the script confusingly reported
in this case that the exit and stop function did not exist.
> Fix #305: trap compiler flags failure in configure

- HEN_HOUSE/src/egsnrc.macros
- HEN_HOUSE/src/egsnrc.mortran
Fix the `AUSCALL` related to relaxation vacancies below the cut-off energy, or in the outer shell. The `AUSCALL` was changed to always treat the energy deposition as though it came from an electron. Previously, it was differentiated based on the charge of the particle initiating the relaxation. All references to `relax_initiator_q` have been removed, since they are no longer used.
This problem was discovered by plotting `mu_en/rho` as a function of energy, using the g application. The value of `mu_en/rho` for air was underestimated, due to the assignment of energy to radiative losses in these vacancy cut-off depositions.
Only applications using `iarg=33` and `34` are affected. Namely, `g` and `dosrznrc`. This bug was introduced in PR #285, commit ba288e0, and was not present in the …
> Fix AUSCALL for relaxation vacancy cut-offs

- HEN_HOUSE/egs++/sources/egs_fano_source/egs_fano_source.cpp
- HEN_HOUSE/egs++/sources/egs_fano_source/egs_fano_source.h
Fix doxygen warnings about an unknown alias for `EMH` in the fano source header file. Now the author is cited correctly.
> Fix doxygen warning about unknown alias

- HEN_HOUSE/specs/egspp1.spec
Added array_sizes.h to the compile dependencies for
egs_interface2.c in egspp1.spec.  As discovered by @ojalaj
when running egs_chamber, without this dependency, changes
to MXSTACK--the max. dimension of variables in the STACK
common block (Fortran)--were not propagated through to
the EGS_Stack definition in egs_interface2.  The result:
mismatched variable dimensions and zero results.
A temporary workaround was to type "make clean" before "make"
after changing MXSTACK.  This forced a recompilation of
egs_interface2.c.
> Fix #318: Bug when changing MXSTACK in array_sizes.h

- HEN_HOUSE/egs++/sources/iaea_phsp_source/iaea_phsp_source.cpp
- HEN_HOUSE/egs++/sources/iaea_phsp_source/iaea_phsp_source.h
1.  Arrays extrafloat_type, extralong_types, extrainttemp,
extrafloattemp, could be initialized with zero dimension if
the IAEA phsp did not store any addition int (e.g. latch)
or float (e.g. zlast) variables for each particle.  These
arrays are now given fixed dimension MAXEXTRAS.
2.  Source had the temerity to actually assign any latch
value read from the phsp file to the incident particle, not
realizing that, at least in the case of egs_chamber, this
variable is used for setting splitting no.  Now, latch is
set to 0, similar to egs_phsp_source.  This partially fixes
the problem that @ojalaj had in Issue #314.
> Fix two bugs in iaea_phsp_source

- HEN_HOUSE/src/egs_utilities.mortran
Allow the `.egsinp` extension in the `-i` argument instead of requiring no extension.
For example, now you can run both `c++` and `mortran` applications with:
```
myApp -i myInput.egsinp
```
instead of being required to use
```
myApp -i myInput
```
I think this was a common beginner mistake and trivial to address. Fix #318.
> Fix #318: Allow extension on input argument

- HEN_HOUSE/egs++/egs_ensdf.cpp
- HEN_HOUSE/egs++/egs_ensdf.h
- HEN_HOUSE/egs++/egs_spectra.cpp
- HEN_HOUSE/egs++/sources/egs_radionuclide_source/egs_radionuclide_source.cpp
- HEN_HOUSE/egs++/sources/egs_radionuclide_source/egs_radionuclide_source.h
- HEN_HOUSE/pegs4/density_corrections/compounds/water_icru90.density
- HEN_HOUSE/specs/egspp1.spec
Add radionuclide beta spectrum exceptions to include some special shape factors. Affected radionuclides are Cl-36, I-129, Cs-137, Tl-204, and Bi-210.
Improve radionuclide source documentation.
Replace instances of `isotope` with `nuclide`. This includes the `EGS_RadionuclideSpectrum` input to specify the radionuclide.
Rename `EGS_RadionuclideSpectrum` input `ensdf fluorescence and auger` to `atomic relaxations` with `eadl` or `ensdf` options for improved clarity.
Also fix #313.
> Add beta spectrum exceptions and change radionuclide inputs

- HEN_HOUSE/egs++/egs_input.cpp
The `include file` input tag in `egs++` apps now calls `egsFatal` if the file does not exist, instead of `egsWarning`. This avoids the warning going unnoticed.
> Fix #326: Missing include file now fatal

- HEN_HOUSE/egs++/egs_base_source.h
- HEN_HOUSE/egs++/egs_input.cpp
Add a method to get the charge of an `EGS_BaseSimpleSource`.
> Fix #321: Add getCharge method to EGS_BaseSimpleSource

- HEN_HOUSE/egs++/egs_application.cpp
Fix a crash that occurs when the egsinp extension is included when launching an egs++ application. Now the extension is stripped if it is included.
> Fix #330: allow input extension in egs++

- HEN_HOUSE/doc/src/pirs898-egs++/cavity.doxy
- HEN_HOUSE/doc/src/pirs898-egs++/egs_chamber.doxy
- HEN_HOUSE/user_codes/cavity/cavity.cpp
Added region labels to `cavity`, similar to what was done for `egs_chamber` previously. Now you can use region labels anywhere you would otherwise type a list of global region numbers!
Also updated the documentation for egs_chamber and cavity to include some description of how to use region labels.
> Add region labels to cavity and docs

- HEN_HOUSE/src/egsnrc.mortran
- HEN_HOUSE/user_codes/examin/examin.mortran
- Print out new photoelectric cross sections by Sabbatucci and Salvat
- Turn ON relaxations if binding effects in Compton considered
- Print *.xsections file only if photons requested
- Reset some defaults
`egsnrc.mortran`: Only print photon binding energies if *.xsections file
output and eadl_relax is true.
> Adjust examin application to recent changes

- HEN_HOUSE/egs++/egs_ensdf.cpp
- HEN_HOUSE/egs++/egs_ensdf.h
- HEN_HOUSE/egs++/egs_spectra.cpp
Fix a bug in `EGS_RadionuclideSource` where the relaxation input `atomic relaxations` required a `yes` or `no` input instead of what was described in the documentation. Now the accepted input is `ensdf`, `eadl`, or `off` with the default as `eadl`.
Also reduced the verbosity of radionuclide spectra.
> Fix radionuclide atomic relaxations input

- HEN_HOUSE/omega/beamnrc/beamnrc.mortran
If a BEAMnrc shared library geometry was interposed
between the source and the phantom and the source
in the BEAMnrc .egsinp was not a phase space or BEAM
simulation source, then the incorrect particle energy
was used to pass the particle through the shared lib.
geometry and, subsequently, on entry to the DOSXYZnrc
phantom.  Quite a dangerous bug.  Recommend patching this
as quickly as possible.
> Fix rest mass and energy in DOSXYZ source 20

- HEN_HOUSE/gui/egs_gui/egs_compile_page.cpp
Passing proper flags to `make` by setting `FOPT` and `opt` variables correctly
- RZ codes use a standard makefile which has defined the targets `opt`, `noopt`, `debug` and `clean`
- C++ Makefiles do not understand these build options. From the `egs_gui` one must adjust the flags according to the user's choice.
> Set egs_gui compilation flags properly

- HEN_HOUSE/omega/beamnrc/BEAMnrc_examples/EXphantom/EXphantom.egsinp
Changed directory path for EX10MeVe.egsphsp1 source
from $HOME/egsnrc/BEAM_EX10MeVe to $EGS_HOME/BEAM_EX10MeVe.
This example can now be run directly without modifying the
input file.  I'd like to get this in place by Trieste 2017!
> Fix EXphantom.egsinp

- HEN_HOUSE/user_codes/egs_cbct/Makefile
- HEN_HOUSE/user_codes/egs_cbct/egs_cbct.cpp
- HEN_HOUSE/user_codes/egs_cbct/egs_cbct.h
- HEN_HOUSE/user_codes/egs_cbct/egs_cbct.macros
- HEN_HOUSE/user_codes/egs_chamber/egs_chamber.cpp
- HEN_HOUSE/user_codes/egs_chamber/egs_chamber.macros
- README.md
Add Iwan Kawrakow as an author of the egs_chamber source code (instead of a contributor).
Fix the top-level readme to state the original release date of EGSnrc, and qualify it as a complete overhaul of EGS (instead of a extended and improved version). Remove the copyright transfer requirement note from the contributing section, because we will be moving to allow external copyrights to be included in the project.
> Fix authorship and readme

- HEN_HOUSE/src/egs_utilities.mortran
Declared common block EGS-IO at top of subroutine replace_env--
the subroutine which allows $ and ~ to be used
at the beginning of file path names--so that i_log is declared for
output.  Don't know why this compiled with no complaints, but the
symptom was actually an incorrect "Job failed" output from
EXphantom runs, first noticed at the EGS/BEAM Workshop in Trieste, 2017.
> Fix variable declaration in subroutine replace_env

- HEN_HOUSE/user_codes/g/g.mortran
Fix a bug where e_mutr and e_muen were nan for a large number of histories and specific seeds. This was due to a rare case where gmfp evaluated to zero. A check was added to catch this case.
> Fix #373: e_mutr is nan in rare case using g

- HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.mortran
If you are using a BEAM shared library geometry with
source 20, it is assumed that the pegs data for the BEAM
geometry is the same as that for DOSXYZnrc.  Previously,
if you ran DOSXYZnrc in pegsless mode, this information was
not correctly passed on to the BEAM simulation.  Now it
is, and the BEAM simulation also runs in pegsless mode.
(Don't forget to define the media in the BEAM input file!)
> Fix #349 Fix pegsless mode in DOSXYZnrc source 20

- HEN_HOUSE/egs++/sources/egs_phsp_source/egs_phsp_source.cpp
- HEN_HOUSE/egs++/sources/egs_phsp_source/egs_phsp_source.h
- HEN_HOUSE/egs++/sources/iaea_phsp_source/iaea_phsp_source.cpp
- HEN_HOUSE/egs++/sources/iaea_phsp_source/iaea_phsp_source.h
Fixes the use of the term `reuse` in the `egs++` phsp sources, instead replacing it with `recycle`. Also fixes the implementation of recycling, so that 1 recycling means that the particle is used twice. 
**Previously, `reuse=1` actually meant that the particle was used once.**
> Fix #334: recycle definition in egs++ phsp sources

- HEN_HOUSE/egs++/sources/egs_beam_source/egs_beam_source.cpp
Due to a floating point comparison, an infinite loop was possible in egs++ applications using a beam shared library source. This was fixed using the epsilon constant.
> Fix #351: Infinite loop using beam source in egs++

- HEN_HOUSE/egs++/sources/egs_fano_source/egs_fano_source.cpp
- HEN_HOUSE/egs++/sources/egs_fano_source/egs_fano_source.h
- HEN_HOUSE/egs++/sources/egs_isotropic_source/egs_isotropic_source.cpp
- HEN_HOUSE/egs++/sources/egs_isotropic_source/egs_isotropic_source.h
- HEN_HOUSE/egs++/sources/egs_radionuclide_source/egs_radionuclide_source.cpp
- HEN_HOUSE/scripts/egsnrc_bashrc_additions
This PR affects only the isotropic source (and hence the Fano source) when used to emit particles into a solid angle defined by a minimum and maximum polar angle theta.
The expression to sample **cos(theta)** between **cos(theta_min)** and **cos(theta_max)** had the terms inverted. While `1-2*rand` produces the same distribution of **cos(theta)** as `2*rand-1` when sampling between 0 and 180 degrees or any angular interval centered around 90 degrees, this is not the case in general when restricting the emission to an arbitrary angular interval between **theta_min** and **theta_max**. One should use the correct expression:
`cos(theta) =  cos(theta_min) - rand * (cos(theta_min - cos(theta_max)))`
rather than
`cos(theta) = -cos(theta_min) + rand * (cos(theta_min - cos(theta_max)))`
In the …
> Fix isotropic emission into solid angle and egs_view alias

- HEN_HOUSE/egs++/geometry/egs_cylinders/egs_cylinders.cpp
- HEN_HOUSE/egs++/geometry/egs_cylinders/egs_cylinders.h
There was a to-do about using `egs_projectors` in `egs_cylinders` instead of its local definition of projectors.
> Use egs_projectors in egs_cylinders

- HEN_HOUSE/user_codes/g/g.make
Adds the required includes for pegsless mode to the g makefile.
> Fix #380: add pegsless to g compilation

- HEN_HOUSE/egs++/egs_base_geometry.cpp
Add a check for duplicate geometry names, and do not allow them. Previously geometries with the same name could produce unexpected results.
**Please check this with some complex input files.** As far as I know geometries are never given the same name intentionally but I could be mistaken.
> Fix #344: Add check for duplicate geometry names

- HEN_HOUSE/user_codes/egs_chamber/egs_chamber.cpp
Initialize the `csplit` variable to 1 by default in the egs_chamber
application constructor; `csplit` is used to read in the radiative
splitting number from the input file.
Previously, `csplit` was only initialized if the input contained a
variance reduction input block. This caused a serious bug to be
introduced in commit 50e0d33, whereby `the_egsvr->nbr_split` was set to
the arbitrary (uninitialized) `csplit` number in the shower loop when
there was no variance reduction input block. If this number happened to
be a large positive integer (about half the time), any radiative event
immediately exceeded the stack size and aborted the simulation.
This probably went unnoticed for so long because one rarely runs
egs_chamber without variance reduction.
> Fix radiative splitting csplit initialization

- HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/DYNJAWS.inp
- HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/DYNVMLC.inp
- HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/SYNCHDMLC.inp
- HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/SYNCMLCE.inp
Fix typos in the documentation for BEAMnrc dynamic CMs. The MUINDEX parameters were not correctly defined. For example, `INDEX(J) >= INDEX(J-1)` is the correct usage of mu indexes. Previously, the documentation stated `INDEX(J) > INDEX(J-1)`.
> Fix #390: docs typo about muindex in dynamic CMs

- HEN_HOUSE/doc/src/pirs701-egsnrc/inputs/new_um_app2.tex
Expand the pirs-701 table 6 to include recently added iarg calls for EII, sub-threshold relaxation photons and electrons.
> Fix #354: Update pirs-701 docs with new iarg

- HEN_HOUSE/user_codes/g/g.mortran
Remove source type options from g, because they are meaningless in an infinite space on a single medium. The options were likely copied over from an old code originally, and contained directional control of the source.
> Fix #384: Remove source types from g

- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.cpp
- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.h
- HEN_HOUSE/egs++/egs_advanced_application.cpp
The EGS_DoseScoring ausgab object has been modified so that
the user now has the option to output doses to a file in
.3ddose format (i.e. standard format for DOSXYZnrc output)
for any EGS_XYZGeometry(ies) in their simulation geometry.
See details in egs_dose_scoring.h.
This is accompanied by a small change to
EGS_AdvancedApplication::finishSimulation().  At the end
of a parallel run, i_parallel is now set to 0.  This allows
us to use EGS_Application::getIparallel() to query whether
or not this is the last job of a parallel run and, only then,
to output a .3ddose file containing the combined results.
> Add option to output .3ddose files to EGS_DoseScoring

- HEN_HOUSE/user_codes/tutor7pp/tutor7pp.cpp
Fix the scoring in tutor7pp so that energy is scored only when it is positive. There are cases when the energy is zero and the region number is -1, which causes memory corruption when the scoring array tries to write to the region index of -1. The fix follows the same scoring method as in egs_chamber.
> Fix tutor7pp scoring to check for positive energy depositions

- HEN_HOUSE/omega/progs/gui/beamnrc/misc_egsnrc.tcl
Figures in all help windows switched to show cross section of most
recent leaf for which the help window was opened.  Fixed by giving
a unique name to the graphic file used in procedure help_gif in
misc_egsnrc.tcl
> Fix #399: Fix bug in DYNVMLC GUI leaf cross section help figures.

- HEN_HOUSE/src/pegs4_macros.mortran
Fix a segmentation fault that occurred when in pegsless mode and a material used in the geometry is missing from the material definitions. Now the code returns gracefully with a fatal error message.
> Fix #398: Seg fault when pegsless material missing

- HEN_HOUSE/user_codes/flurznrc/flurznrc.mortran
For non-phase space sources, results from individual jobs were
normalized by the same total fluence (AINFLU) as the combined jobs.
This has been corrected so that AINFLU is adjusted to reflect the
number of histories run by a given job.  Somewhat frighteningly,
the original coding had AINFLU adjusted correctly but only if the
job couldn't execute within the user input max. CPU time.
> Fix #403: Fix flurznrc normalization of individual || jobs

- HEN_HOUSE/egs++/egs_interpolator.h
- HEN_HOUSE/user_codes/cavity/cavity.cpp
The charged particle fluence calculation in cavity was recently modified to provide the actual fluence rather than the product fluence times stopping power. To this end, the quantity scored at each energy bin was divided by the stopping power `Li` at the lower energy edge of the corresponding bin `i`. This is correct for the initial energy bin and the bins fully covered during the step. However at the final bin, the particle's energy at the end of the step doesn't always coincide with the lower energy edge of that bin and using that initial approach introduces an artifact. One could use the stopping power at the mid-energy of the bin, but it also introduces an artifact. Both cases can produce significant differences in the differential flluence and non-negligible differences in the total …
> cavity e-/e+ fluence calculation redux

- HEN_HOUSE/src/egsnrc.mortran
- HEN_HOUSE/src/emf_macros.mortran
Adjust the charged particle step routine for transport in vacuum when
there is an electromagnetic field (emf). The existing logic failed
because the emf step size restriction was not taken into account before
the howfar call. Hence the howfar method tracked the particle in a
single straight step across the entire vacuum region, causing erroneous
region changes and discards.
> Fix #413: limit vacuum step size in magnetic field

- HEN_HOUSE/egs++/egs_particle_track.cpp
- HEN_HOUSE/egs++/egs_particle_track.h
Fix a crash that occurred often when using tracks on Windows 10. The crash started happening with a Windows update, and resulted in a segmentation fault when generating the first track in the simulation. The crash occurred due to accessing an array index out of bounds in the tracks generation (not sure why this didn't crash previously).
Fixes issue #385, from what I can tell.
This is an important functionality fix and should be added to master.
> Fix egs++ particle tracks crash on Windows 10

- HEN_HOUSE/src/egsnrc.mortran
Assign the current particle region, ir(np), to the old region index,
irold, within the ustep loop in electron transport. Previously, irold
was not updated, so the irnew ~= irold condition added to fix magnetic
field transport in vacuum caused zero-size steps to skip the region
change macro. Remove the now redundant irold = ir(np) assignment in the
non-zero step size block.
> Fix #425: irold not updated in electron step loop

- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.h
- HEN_HOUSE/egs++/egs_base_geometry.cpp
- HEN_HOUSE/egs++/egs_base_geometry.h
- HEN_HOUSE/egs++/sources/egs_fano_source/egs_fano_source.h
- HEN_HOUSE/egs++/view/clippingplanes.cpp
- HEN_HOUSE/egs++/view/clippingplanes.h
- HEN_HOUSE/egs++/view/clippingplanes.ui
- HEN_HOUSE/egs++/view/egs_track_view.cpp
- HEN_HOUSE/egs++/view/egs_track_view.h
- HEN_HOUSE/egs++/view/egs_visualizer.cpp
- HEN_HOUSE/egs++/view/egs_visualizer.h
- HEN_HOUSE/egs++/view/image_window.cpp
- HEN_HOUSE/egs++/view/image_window.h
- HEN_HOUSE/egs++/view/main.cpp
- HEN_HOUSE/egs++/view/renderworker.cpp
- HEN_HOUSE/egs++/view/renderworker.h
- HEN_HOUSE/egs++/view/view.pro
- HEN_HOUSE/egs++/view/viewcontrol.cpp
- HEN_HOUSE/egs++/view/viewcontrol.h
- HEN_HOUSE/egs++/view/viewcontrol.ui
**New egs_view layout, settings file, dose viewing and more..**
- Added the ability to save & load a configuration file for `egs_view`. This includes saving the current look orientation, window size, track options, clipping planes, etc. You can load the config file from the GUI, or pass it as an argument (with or without ptracks file argument). E.g.
`egs_view myInput.egsinp myInput.egsview`
- Fixed various segmentation faults that occurred when reloading files. This includes a fix to clearGeometries() in egs_base_geometry so that composite geometries actually get cleaned up. Added an option to load a new input file.
- Changed the layout - now there are tabs to divide sections, and the more commonly used options are together. Also, clipping planes are more intuitive! The key-bindings can …
> Update egs_view layout

- HEN_HOUSE/gui/egs_gui/egs_compile_page.cpp
- HEN_HOUSE/gui/egs_inprz/src/inputRZForm.cpp
- HEN_HOUSE/gui/egs_inprz/src/inputRZImpl.cpp
Fix a bug in the Qt GUI compilation functions. The make program from the
config may contain a space if it was provided arguments like -j12. Now
the Qt gui splits the string if there are spaces, so that it can
determine the make program correctly.
Also fix a bug on the odroid OS where the egs_inprz tooltip default
text color did not contrast with the tooltip background. This was fixed
by setting those colors explicitly.
> Fix Qt GUI compile functions and tooltip

- HEN_HOUSE/src/get_inputs.mortran
Fix the photon cross sections transport parameters initialization, when the user does not specify a value.
Although the correct default value was used when this parameter was not specified, some corrupted text was output to the egslst file. **This minor bug did not affect results, only the display of the egslst file in some editors.** Now, the variable is initialized in the same way as the compton cross section variable.
> Fix #359: photon cs parameter not initialized

- HEN_HOUSE/egs++/Makefile
- HEN_HOUSE/egs++/ausgab_objects/egs_radiative_splitting/Makefile
- HEN_HOUSE/egs++/ausgab_objects/egs_radiative_splitting/egs_radiative_splitting.cpp
- HEN_HOUSE/egs++/ausgab_objects/egs_radiative_splitting/egs_radiative_splitting.h
- HEN_HOUSE/egs++/egs_advanced_application.cpp
- HEN_HOUSE/egs++/egs_advanced_application.h
- HEN_HOUSE/egs++/egs_application.h
A first step for implementing the variance reduction technique (VRT) _radiative splitting_ via an AO making this VRT available to any C++ application. It simply turns on the intrinsic _uniform radiative splitting_ in `EGSnrc` by setting `nbr_split` to a user-defined value which can have the following effects:
- If `nbr_split > 1`: uniform radiative splitting (URS) is ON
- If `nbr_split = 1`: no radiative splitting
- If `nbr_split < 1`: Radiative events OFF !!!
This should make possible the efficient simulation of electronic brachytherapy sources. It will also allow modelling x-ray tubes and linacs albeit less efficiently than the DBS technique as implemented in `BEAMnrc`. The next step is to implement _directional radiative splitting_ which would increase the efficiency in the simulation …
> Radiative splitting ausgab object (AO)

- HEN_HOUSE/src/get_media_inputs.mortran
Increased the length of TEXTPIECE, an intermediate variable
into which lines from .egsinp are read, from character*80 to
character*256.  Long strings, such as those defining density
correction files in non-default locations, were being cut off.
> Fix length of text line in get_media_inputs.mortran

- HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.mortran
Fixed a bug in inputs for sources 20, 21 in which the code
hung if the user indicated that a shared library geometry was not
to be included by inputting a blank (instead of a '0')
for the name of code defining the shared library geometry.
While fixing this, other input bugs related to incorrect
use of the Fortran len(char) were found and fixed.
> Fix #430: Fix blank inputs for DOSXYZnrc sources

- HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.mortran
Fixed by calling sample_vcusource with zsrcdum.  Thanks to @mchamberland
for spotting the bug and the fix.
> Fix #437: Prevent call to vcusource from overwriting zsrc.

- HEN_HOUSE/egs++/geometry/egs_planes/egs_planes.cpp
- HEN_HOUSE/egs++/geometry/egs_prism/egs_prism.h
- HEN_HOUSE/egs++/geometry/egs_pyramid/egs_pyramid.cpp
Fixes the number of regions assigned to egs_prism geometries. Now nreg is set to 1 instead of defaulting to 0. Previously, this would result in region labels not working.
Comments out two warning messages that always occurred for `egs_planes` and `egs_pyramids.` This does not change any functionality.
> Fix egs_prism number of regions set to zero

- HEN_HOUSE/cutils/load_beamlib.c
- HEN_HOUSE/egs++/sources/egs_beam_source/egs_beam_source.cpp
- HEN_HOUSE/egs++/sources/egs_beam_source/egs_beam_source.h
- HEN_HOUSE/omega/beamnrc/beam_lib.mortran
- HEN_HOUSE/omega/beamnrc/beamnrc.mortran
- HEN_HOUSE/omega/beamnrc/beamnrc_user_macros.mortran
- HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.mortran
- HEN_HOUSE/utils/srcrz.mortran
Previously, a parallel run using a beam simulation source that used a
phase space source either hung or crashed due the fact that the
variables defining the record no. to be read from the phase space
source (INPHSP) and the segment of the phase space source considered
(INPHSP_MIN, INPHSP_MAX) were undefined.  Now, each parallel job is
uses a segment of the phase space source restricted by:
(i_parallel - 1)*(NNPHSP/n_parallel)+1 <= INPHSP <=
(i_parallel)*(NNPHSP/n_parallel)
where n_parallel is the no. of parallel jobs, i_parallel is the job
number, and NNPHSP is the total no. of particles in the phase space
source.
> Fix #447: Fix parallel runs with beam sim. source using phase space

- HEN_HOUSE/egs++/geometry/egs_cylinders/egs_cylinders.cpp
- HEN_HOUSE/egs++/view/renderworker.cpp
- HEN_HOUSE/egs++/view/viewcontrol.cpp
- HEN_HOUSE/egs++/view/viewcontrol.h
Fix the egs_view simulation geometry selection so that only geometries that are actually named in the input file can be selected. When selecting the simulation geometry, the view window now resets the camera position to find a point within the new geometry.
Fix a bug where the axis did not display correctly at certain view angles when the geometry was not near the origin.
Fix a bug in egs_cylinders where the geometry type was not defined. This was only necessary so that the type was displayed correctly in egs_view.
> Fix egs_view simulation geometry selection

- HEN_HOUSE/pieces/help_message
This replaces pull request #429. The only change is the removal of the double period after "etc." and an edit of the commit title.
> Fix typos in help_message text file

- HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
Changed input format to (*) from (3I5).
> Fix #409: Relax input format for .egsphant dimensions.

- HEN_HOUSE/omega/progs/gui/beamnrc/help.tcl
On pressing the help icon within the window for
setting directional source biasing (DSB) parameters,
the same text as that associated with the DSB help
button in the source 3 input window comes up.
> Fix DSB help dialog in beamnrc_gui

- HEN_HOUSE/doc/src/pirs509a-beamnrc/pirs509a-beamnrc.tex
- HEN_HOUSE/doc/src/pirs702-egsnrc-codes/pirs702-egsnrc-codes.tex
- HEN_HOUSE/doc/src/pirs794-dosxyznrc/pirs794-dosxyznrc.tex
- HEN_HOUSE/gui/egs_configure/egs_tools.cpp
- HEN_HOUSE/scripts/configure
- HEN_HOUSE/scripts/configure_c++
Update the default gcc optimization configuration to use -march=native
instead of -ffast-math. The latter causes various floating-point
exceptions on newer cpus and compilers. If the programs are run on a
different cpu, then one should use the corresponding -march option for
that architecture instead of "native", or else use the less aggressive
-mtune=native if the compiling and running cpus are in the same family.
The alternatives -march and -mtune were suggested by @Kawrakow in 
issue #174.
See also #85, #91, #174, #204 and #423.
> Fix #423: change -ffast-math to -mtune=native

- HEN_HOUSE/egs++/egs_advanced_application.cpp
- HEN_HOUSE/interface/egs_interface2.h
- HEN_HOUSE/src/egs_utilities.mortran
- HEN_HOUSE/src/egsnrc.macros
- HEN_HOUSE/src/egsnrc.mortran
- HEN_HOUSE/src/emf_macros.mortran
- HEN_HOUSE/src/get_inputs.mortran
Add the boolean variable emfield_on which is set to true if the
electromagnetic field (emf) is not null. This flag is used in the
emf_macros to skip all field related computations when there is no
field.
Ideally the file emf_macros.mortran would not be included at all in the
compilation when there is no field, but it proves impractical and error
prone to change the Makefile and recompile upon changing the input
parameters. The emfield_on flag allows the emf_macros to be integrated
by default, yet not waste time at each step when the field is 0.
> Add a flag to specify if EM fields are on or off

- HEN_HOUSE/scripts/configure
- HEN_HOUSE/scripts/configure.expect
Update the C compiler selection logic (to match the fortran compiler
selection logic) which allows the selection of any C compiler available
on the search path, or via a full path. Previously, the C compiler name
was constrained to a hard-coded list.
Also adjust the filtering of the configuration file name to enforce a
single .conf extension. Previously, the file name was taken as is, and
any extension starting from the last dot was removed to yield the
configuration base name. This proved error-prone when trying to use
names with version numbers, such as gcc-4.8 for example.
> Fix #176: relax C compiler selection and conf name

- HEN_HOUSE/egs++/Makefile
- HEN_HOUSE/egs++/egs_base_source.h
- HEN_HOUSE/egs++/sources/egs_beam_source/egs_beam_source.cpp
- HEN_HOUSE/egs++/sources/egs_beam_source/egs_beam_source.h
- HEN_HOUSE/egs++/sources/egs_dynamic_source/Makefile
- HEN_HOUSE/egs++/sources/egs_dynamic_source/egs_dynamic_source.cpp
- HEN_HOUSE/egs++/sources/egs_dynamic_source/egs_dynamic_source.h
- HEN_HOUSE/egs++/sources/egs_transformed_source/egs_transformed_source.h
- HEN_HOUSE/egs++/sources/iaea_phsp_source/iaea_phsp_source.cpp
- HEN_HOUSE/egs++/sources/iaea_phsp_source/iaea_phsp_source.h
An EGS_DynamicSource allows the user to simulate dynamic (time-varying)
motion of any source during a single calculation.  Continuous motion
of the source is simulated between user-defined control points, where
each control point defines a set of incident polar coordinates and an
associated fractional monitor unit (mu) index.
If the source is an IAEA-format phase space file or a BEAM simulation
source, then, provided the source stores the value of mu for each
particle, the user has the option to use these when setting incident
source coordinates, thus synchronizing the motion of EGS_DynamicSource
with jaw and MLC opening coordinates in the upstream BEAM simulation.
For phase space and BEAM simulation sources, EGS_DynamicSource
essentially provides the same functionality as sources 20 and …
> Add EGS_DynamicSource class

- HEN_HOUSE/egs++/Makefile
- HEN_HOUSE/egs++/ausgab_objects/egs_phsp_scoring/Makefile
- HEN_HOUSE/egs++/ausgab_objects/egs_phsp_scoring/egs_phsp_scoring.cpp
- HEN_HOUSE/egs++/ausgab_objects/egs_phsp_scoring/egs_phsp_scoring.h
- HEN_HOUSE/egs++/egs_advanced_application.cpp
- HEN_HOUSE/egs++/egs_advanced_application.h
- HEN_HOUSE/egs++/egs_application.h
- HEN_HOUSE/iaea_phsp/iaea_header.cpp
This ausgab object allows the user to score phase space files in EGSnrc or
IAEA format for particles entering/exiting a predefined geometry.
See the documentation at the the top of egs_phsp_scoring.cpp for more
details.
It has been tested for a single scoring plane perpendicular to the Z axis.
However, testing for other and more complex geometries is encouraged and
required!
The commit also includes a small change to the check_byte_order() function
in iaea_header.cpp: The function, which is called every time an IAEA header
file is updated, no longer outputs the byte order (along with an outdated
list of associated architectures) to the screen.  This was resulting in
a lot of cryptic screen output when writing IAEA phase space files.
> Add egs_phsp_scoring ausgab object.

- HEN_HOUSE/src/egsnrc.macros
- HEN_HOUSE/src/egsnrc.mortran
This PR fixes the following bug:
**Symptoms:** Simulations crashing (segmentation fault) for Pa, U, Np,
and Cm when using EADL atomic relaxation.
**BUG:** Number of maximum transitions was fixed in egs_init_relax to 250
via the local macro $MAXTMP. However some elements have a larger
number of transitions, the maximum being 270 for curium (Cm).
**FIX:** Increase size of the arrays to 300.
**CHANGE:** Using now global macro $MAXTRANS
> Thanks to Jason Bolton from Nordion who encountered the segmentation fault and to @rtownson who tracked it back to being related to relaxations.
> Fix bug in atomic relaxation of some actinides

- HEN_HOUSE/egs++/egs_base_source.h
- HEN_HOUSE/egs++/egs_spectra.cpp
- HEN_HOUSE/egs++/sources/egs_radionuclide_source/egs_radionuclide_source.cpp
- HEN_HOUSE/egs++/sources/egs_radionuclide_source/egs_radionuclide_source.h
A number of radionuclide source refinements.
1. Adds the option for a collimated radionuclide source. This is done by setting `source type = collimated` in the radionuclide source block.
2. Reduces the scope of radionuclide source specific methods, instead of declaring them at the base source and spectrum levels. The radionuclide source now statically casts the spectrum to a radionuclide spectrum in order to access the special methods, and applications should do the same to access the radionuclide source methods.
3. Adds an `experiment time` parameter to the radionuclide source, so that emissions can be restricted according to their emission times. These emissions that would be outside the measurement time get returned by the source as zero energy particles.
4. Adds a method to query the …
> Add radionuclide source refinements (collimated source, experiment time ...)

- HEN_HOUSE/scripts/finalize_egs_foruser
- HEN_HOUSE/user_codes/egs_app/Makefile
- HEN_HOUSE/user_codes/egs_app/array_sizes.h
- HEN_HOUSE/user_codes/egs_app/egs_app.cpp
- HEN_HOUSE/user_codes/egs_app/slab.egsinp
Provide the simplest possible EGSnrc application, which relies on the
implementation of EGS_AdvancedApplication, to run a simulation described
in an egs++ input file (the provided slab.egsinp, for example).
The code commented below APP_MAIN can serve as a template for deriving an
application class from EGS_AdvancedApplication, and re-implementing the
initScoring method to select ausgab call triggers, and the ausgab method
to handle those calls.
> Add a simple template egs++ application egs_app

- HEN_HOUSE/egs++/Makefile
- HEN_HOUSE/egs++/ausgab_objects/egs_radiative_splitting/Makefile
- HEN_HOUSE/egs++/egs_ensdf.h
Fixes a bug where the egs++ library did not compile on windows. This bug did *not* make it into the `master` release, and has only been in the `develop` branch since commit 68a830d.
The failure was due to a typo in the radiative splitting ausgab Makefile, and due to some missing EGS_EXPORT flags in egs_ensdf for the radionuclide source.
> Fix windows compilation bug

- HEN_HOUSE/gui/egs_configure/egs_tools.cpp
- HEN_HOUSE/pieces/tests_win.xml
**Bug:** Parallel runs on Windows were failing to combine `*.egsdat `files. Reported by Alex Bielajew.
**Cause:** check for exit status from the `system` function and subroutine was failing on Windows. 
As a consequence, a dummy `egs_system `funtion always returned a successful command execution status.
One can now submit parallel jobs on Windows to all available cores on a given PC and get the combined results.
> Fix Win egs_system function

- HEN_HOUSE/src/egsnrc.macros
- HEN_HOUSE/src/get_inputs.mortran
**Please review this PR carefully - will the `CHAR_VALUE` change cause problems elsewhere?**
Fixed a bug where simulations would not read the input for the density correction file if specified in a material file. The error looked like this:
```
***************** Error:
Error: Cannot open density correction file:
.density
***************** Quiting now.
```
This error only occurred on certain systems. It was due to a string assignment mismatch between 256 and 80 characters, resulting in an empty string. The bug only existed since PR #445, which extended one string to 256 characters.
The error can be produced by adding the following to the EX10MeVe.egsinp example, and running on a gcc 4.5.1 system.
```
:start media definition:
AE=0.521
UE=18.021
AP=0.01
UP=18.5
material data …
```
> Fix #485: string size mismatch in media inputs

- HEN_HOUSE/egs++/view/viewcontrol.ui
Fix a bug that caused `egs_view` to not compile, giving an error about including `vector.h`. This include statement has been removed since it is not necessary. This has been tested both on qt4 and qt5.
> Fix egs_view compilation

- HEN_HOUSE/egs++/egs_base_geometry.cpp
- HEN_HOUSE/egs++/egs_base_geometry.h
- HEN_HOUSE/egs++/geometry/egs_box/egs_box.h
- HEN_HOUSE/egs++/geometry/egs_cd_geometry/egs_cd_geometry.h
- HEN_HOUSE/egs++/geometry/egs_cones/egs_cones.h
- HEN_HOUSE/egs++/geometry/egs_cylinders/egs_cylinders.h
- HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.h
- HEN_HOUSE/egs++/geometry/egs_spheres/egs_spheres.cpp
1. Fix a special case of geometry error where geometries that are convex individually result in a concave cd geometries when combined (issue #388). These geometry errors could be created using a radius-mismatched cylinder and sphere in a cd geometry. Also fix where a small step is taken in cylinder or sphere howfar routines to step by boundaryTolerance/2 instead of boundaryTolerance. This resulted in checks against the boundaryTolerance to fail in the cd geometry.
2. Fix a geometry error where particles could get stuck on an edge of an XYZ geometry used as the base geometry for a CD inscribed in an envelope (issue #383).
3. Fix an infinite loop that could occur in long simulations with a conestack with more than one layer. Previously, particles could get stuck on the surface between …
> Fix #388, #383: concave CD, XYZ inside CD, conestack, and box geometry errors

- HEN_HOUSE/src/get_inputs.mortran
Fix the line length that was longer than 80 characters in get_inputs.mortran. This mistake was added in PR #510 just now, so likely no one will experience any issues from this.
> Fix egs_inputs line length

- HEN_HOUSE/egs++/egs_ensdf.cpp
- HEN_HOUSE/egs++/egs_spectra.cpp
Fix a bug where the Auger electrons from atomic relaxations during `egs_radionuclide_source` source generation were not produced. This did not affect atomic relaxations in EGSnrc in general, only the radionuclide source when it was set to `EADL` relaxation mode. The Auger electrons were excluded because the relaxation code expected `ECUT` to be provided in kinetic energy instead of total energy. Since Auger electrons are low energy, they were all thus below the cutoff.
Also improve compatibility with the BNL and IAEA ENSDF databases.
> Fix radionuclide source Auger electrons for EADL relaxations

- HEN_HOUSE/src/EEMF_macros.mortran
- HEN_HOUSE/src/EEMF_macros_beamrc.mortran
- HEN_HOUSE/src/egsnrc.macros
- HEN_HOUSE/src/egsnrc.mortran
These changes are to include the electric and magnetic field transport that is based on a higher numerical integration algorithm for the condensed history algorithm, analytical transport in a magnetic field for the single scatter, and specialized boundary crossing for the EM-field.
This code is accompanied by a report that describes how to implement and use the EEMF macros (EMFMacrosInEGSnrcReport.pdf](https://github.com/nrc-cnrc/EGSnrc/files/704931/EMFMacrosInEGSnrcReport.pdf).
> Enhanced EM transport

- HEN_HOUSE/egs++/geometry/egs_cones/egs_cones.h
This reverts commit 9f94ea42a1b968fa89a932f2eb6a342978e2a504. The original commit was intended to fix an infinite loop in the conetack geometry, but ended up also introducing geometry errors in long simulations of ionization chambers. 
Additionally, I was not able to reproduce the original infinite loop issue after reverting the change (though it does reappear when I switch to v2018). There have been no other changes in the conestack geometry since then, so I am unsure what else might have fixed the issue. Maybe it was a rare event and the same seeds no longer generate the same path, so I am running longer simulations to check.
This commit should get added to master and we should add a v2019a tag to update the release.
> Revert "Avoid infinite loop in conestack geometry"

- HEN_HOUSE/src/egsnrc.mortran
Fix an infinite loop that could happen due to floating point errors in the annihilation routine. The COSTHE variable could end up being slightly less than -1, resulting in a NAN when used in square root.
> Fix #535: infinite loop during annihilation

- HEN_HOUSE/egs++/egs_application.cpp
Fix a `Windows PowerShell` and `git bash` bug where the .exe extension on applications was included in the app_name variable. This resulted in a runtime error where the input file failed to be found. Now we check to see if there is a .exe at the end of the app_name, and remove it.
> Fix #528: Windows PowerShell bug with .exe in app_name

- HEN_HOUSE/omega/progs/gui/dosxyznrc/load_input2_nrc.tcl
- HEN_HOUSE/omega/progs/gui/dosxyznrc/reset_parameters_nrc.tcl
- HEN_HOUSE/omega/progs/gui/dosxyznrc/set_main_inputs_egsnrc.tcl
- HEN_HOUSE/omega/progs/gui/dosxyznrc/xyznrc_parameters.tcl
inputs in DOSXYZnrc GUI.
These are really only relevant for parallel runs using
the deprecated pprocess Unix/Linux script.  Moreover,
having these inputs accessible through the GUI never really made
sense anyway, because the script changed them automatically.
> Remove IPARALLEL and PARNUM options from main

- HEN_HOUSE/egs++/egs_application.cpp
Fix a bug that caused any of the characters in ".exe" found in an application name or input file to crash the run. This happened due to a mistaken use of `find_last_of()` instead of `rfind()` when searching for an extension on the application name. 
This bug only made it into the `develop` branch for 1 day.
> Fix bug introduced by PR #532

- HEN_HOUSE/omega/beamnrc/beamnrc.mortran
Base setting if I_MU_PHSP (scoring of MU index
in IAEA format phase space files) on whether
characters 1-4 of CMNAME for any module in the
accelerator are 'SYNC'.  Replaces check on full
value of CMNAME.  The latter check failed if the only
synchronized CM was SYNCHDMLC, in which case
CMNAME can never be equal to 'SYNCHDMLC' because
CMNAME is character*8!
Resolves Issue #533
> Fix #533: check on synchronized modules

- HEN_HOUSE/egs++/view/egs_track_view.cpp
- HEN_HOUSE/egs++/view/viewcontrol.cpp
Fix invalid memory accesses that lead to crashes in Windows when loading tracks in egs_view. These bugs were introduced in PR #427.
> Fix tracks crashing egs_view in Windows

- HEN_HOUSE/user_codes/dosrznrc/dosrznrc.mortran
Change two variable names in DOSRZnrc to be consistent with a recent publication, Rogers and Townson 2019. The variables `before_eii` and `before_photo` are now `during_eii` and `during_pe_comp`.
> Change two variable names in DOSRZnrc

- HEN_HOUSE/doc/src/pirs509a-beamnrc/inputformats/SYNCHDMLC.inp
- HEN_HOUSE/doc/src/pirs509a-beamnrc/pirs509a-beamnrc.tex
- HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_cm.mortran
- HEN_HOUSE/omega/progs/gui/beamnrc/beamnrc_params.tcl
- HEN_HOUSE/omega/progs/gui/beamnrc/synchdmlc.tcl
Allows more accurate modeling of Varian HD 120 MLC.  Accompanying
changes to GUI and documentation included.
> Fix #489: Allow odd no. of TARGET/ISOCENTER leaves in SYNCHDMLC

- HEN_HOUSE/src/EEMF_macros.mortran
- HEN_HOUSE/src/EEMF_macros_beamnrc.mortran
Fixes a compile error for EEMF beamnrc macros, due to an undeclared variable being used in an error message. Renames the BEAMnrc macros file to fix a typo in the filename. Removes a couple unused constants.
> Fix #554: Compile error when BEAMnrc EEMF macros are used

- HEN_HOUSE/egs++/egs_alias_table.cpp
- HEN_HOUSE/egs++/egs_alias_table.h
- HEN_HOUSE/egs++/sources/egs_source_collection/egs_source_collection.h
1. Fixed phsp support in the `egs_source_collection`, that was due to not defining `setSimulationChunk`. It has been added to match what already exists in `egs_transformed_source`. The bug meant that parallel runs using phase-spaces in a source collection would not have the parallel "chunks" starting at different locations in the phsp. Instead, all chunks would start at the beginning of the phsp, effectively resulting in extra recycling of those particles. In highly parallel or low number of particle simulations, this would affect the statistics and potentially introduce latent phase-space variance artifacts.
2. Fixed a bug in `EGS_SimpleAliasTable` where certain series of weights did not result in correct sampling. For example, using weight = 10 10 1 1 in a source collection resulted in …
> Fix source collection and simple alias table

- HEN_HOUSE/egs++/egs_polygon.h
- HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.h
- HEN_HOUSE/egs++/geometry/egs_prism/egs_prism.h
**Fix 3 different geometry errors that all arose when both an XYZ geometry and a prism were used in a CD geometry.** 
1. In the `howfar` routine in `egs_prism.h`, a step inside the geometry commonly returns exactly the distance to the boundary. However, due to floating point error the code still saw the particle as inside the geometry despite expecting to be outside. The error is avoided by adding a push to ensure we are now outside the surface. I feel like a more refined solution is possible, can anyone do better?
```
if (tt > 0) {
t = tt+boundaryTolerance;
} else {
t = tt;
}
```
2. In `egs_nd_geometry.h`, steps of `t = boundaryTolerance` could fail against checks including the boundary tolerance in a CD geometry. Changing the steps to `halfBoundaryTolerance` fixed this. This solution …
> Fix geometry errors for prism and XYZ in a CD

- HEN_HOUSE/egs++/geometry/egs_autoenvelope/Makefile
- HEN_HOUSE/egs++/geometry/egs_glib/Makefile
- HEN_HOUSE/egs++/geometry/egs_rz/Makefile
Fix compilation of egs_glib and egs_rz geometries on windows. This bug was introduced in PR #103 that added the geometries.
> Fix glib and egs_rz windows compilation

- HEN_HOUSE/doc/src/pirs509a-beamnrc/pirs509a-beamnrc.tex
- HEN_HOUSE/omega/beamnrc/CMs/SYNCHDMLC_cm.mortran
Allows users to backproject cross-section dimensions
to ZMIN without encountering input errors.  It turns out that many
SYNCHDMLC users interpret the manufacturer-supplied data for HD120
leaves in this way, and relaxing these restrictions may allow them
to better approximate divergent leaf sides.  Thanks to Dr. Jarkko
Ojala for pointing out which restrictions need to be relaxed and
testing the modified code.
> Relax certain restrictions on leaf cross-section dimensions.

- HEN_HOUSE/user_codes/sprrznrc/sprrznrc.mortran
Fix a bug in the sprrznrc output of D/Dmax vs radius. The indices of the y coordinate and uncertainty were using the z index instead of looping over the x index.
> Fix #607: Bug in sprrznrc output of D/Dmax

- HEN_HOUSE/scripts/configure
Fix a bug in the configure script where it would crash if there was a space in the linux group name while checking for the record length. Now the `stat` command is used instead of `ls` to find the size of a file.
Thanks to @FredericBrochu for the debugging and solution.
> Fix #616: Space in group name crashes configure script

- HEN_HOUSE/user_codes/dosrznrc/dosrznrc.mortran
Fix the DOSRZnrc kerma calculation so that sub-threshold fluorescent photons (`iarg=33`) are included in the kerma. This bug meant that `D/K` and `D/Kcol` were not equal to 1 for some cases, up to about a 0.8% difference. This makes the algorithm slightly different from the g app, where only primary photons are considered, because DOSRZnrc includes the kerma from secondary photons.
Add some output formatting improvements to DOSRZnrc. Also add the `IDC` or I Double Count variable to allow the user to avoid including k.e. released by any bremsstrahlung or 511 photons. Some comments are also added to improve the readability of the code, and a never-reached code block was removed.
Thanks to Dave Rogers and Ernesto for all their work on these improvements!
> Fix minor bug in DOSRZnrc kerma calculation

- HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
Fix a typo where `PCUTIN` was not set to `PCUT` when `PCUTIN<PCUT`. Also add floating point guard.
> Fix #608: Typo in DOSXYZnrc PCUT input check

- HEN_HOUSE/omega/progs/addphsp/addphsp.mortran
Fix the addphsp usage text to describe the required input better. This is now consistent with phsps produced from egs++, instead of assuming BEAMnrc.
> Fix the addphsp usage text

- HEN_HOUSE/omega/beamnrc/CMs/CHAMBER_cm.mortran
- HEN_HOUSE/omega/beamnrc/beamnrc.mortran
Fixed bug in CHAMBER where identical zones
in central part were automatically assigned
sequential dose zone numbers even if the user
input 0 for the first layer.
Also, suppress dose output in zones with zero
mass.
> Fix CHAMBER dose zone numbering

- HEN_HOUSE/omega/beamnrc/beamnrc.mortran
The bit region of origin was not stored in latch bits 24-28 of fluorescent photons.
With no splitting, this is done using a call to ausgab with `iarg=$EIIA` (flag denoting eii just occurred), looping through `npold...np` and labeling all resultant photons.
With UBS and DBS, we label fluorescent photons prior to calling uniform splitting routines. While this is slight overkill (it "relabels" fluorescent photons from Compton and photoelectric
relaxations), it is necessary for eii because of the redefinition of `npold` in these cases.
> Label fluorescent photons from eii as secondary.

- HEN_HOUSE/egs++/egs_functions.cpp
- HEN_HOUSE/egs++/egs_functions.h
- HEN_HOUSE/egs++/egs_spectra.cpp
- HEN_HOUSE/user_codes/cavity/cavity.cpp
- HEN_HOUSE/user_codes/egs_cbct/egs_cbct.cpp
- HEN_HOUSE/user_codes/egs_cbct/example_w5br.egsinp
- HEN_HOUSE/user_codes/egs_fac/egs_fac.cpp
- HEN_HOUSE/user_codes/egs_fac/examples/example_mees_250kV.egsinp
- HEN_HOUSE/user_codes/egs_fac/examples/mxr-320-250kVp_tube.egsinp
- HEN_HOUSE/user_codes/egs_kerma/egs_kerma.cpp
- HEN_HOUSE/user_codes/egs_kerma/example_40keV_SDD_1m_FD.egsinp
Introduces the C++ EGSnrc global function `egsExpandPath` to search for _**one**_ environment variable _anywhere_ in the string argument and expand it with its value. It understands Unix (`$VAR`) and Windows (`%VAR%`) environment variables, as well as their file separators (backslash or slash). However the file name is output using slashes as file separators. Consequently:
- Spectrum file names can now include an environment variable such as `$EGS_HOME` or `$HEN_HOUSE`
- C++ apps requesting input of a file name were updated to use this feature
- egs++ spectrum file names can also use environment variables
This feature matches the functionality already existing for Mortran apps although with added flexibility.
> Feature expand environment variable in file names for C++ apps

- HEN_HOUSE/egs++/egs_input.cpp
Fixes file includes in egs++, so that the external file content is inserted into the total input file content before everything else is processed. This fixes a bug where composite geometries that referenced a geometry in the external file would crash, because the external geometry hadn't been
loaded and assigned a name yet.
> Fix file includes in egs++ input files

- HEN_HOUSE/user_codes/egs_chamber/egs_chamber.cpp
Fix the ECUT check in `egs_chamber` that is used when a user selects the `ECUT regions` specifically in their calculation geometry. The bug was that the rest mass was subtracted from the particle energy during the ECUT comparison, effectively resulting in the ECUT being 0.511 MeV higher than it should have been. **This is a significant bug!** It looks like this line has been there for as long as we have a git history of egs_chamber. Please double check to be sure I'm not mistaken on how the ECUT should be handled here.
Thanks to /u/LuisDFQ on the Reddit community for pointing out that `ECUT regions` gave a different result than just using a global ECUT of the same value.
> Fix the egs_chamber region-specific ECUT check

- HEN_HOUSE/cutils/egs_c_utils.c
Related to Issue #438 and Pr #368 Modifies the locking wait mechanic on the job lock file. The old method would have everything wait 12 seconds and try again. This system introduces a randomizer to reduce double collisions and future collisions. This has been tested on pbs based clusters with NFS and HDD storage.
I also ran astyle --options=..egs_style_standard over the file.
> Complex lock file locking for issue #438 

- HEN_HOUSE/gui/egs_configure/egs_tools.cpp
Fix a type mismatch of a variable that resulted in compilation errors. Newer compilers are strict about the type matching correctly, though only the windows compiler mingw seemed to throw an error.
> Fix an egs_configure compilation error on Windows

- HEN_HOUSE/omega/progs/ctcreate/ctcreate.mortran
- HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
Change the egsphant reading/writing algorithms in ctcreate and DOSXYZnrc so that up to 95 materials are allowed. Previously, for media indices greater than 9 they were replaced with `*` and the resulting egsphant file would not be valid, resulting in a crash in DOSXYZnrc.
As per Fred's suggestion below, the full range of 95 ASCII printable characters are used for the material indices in the egsphant file. This makes the file slightly less human-readable, but is backwards compatible (expanding to 2 digits per index is not). I made a change from his indexing scheme so that it starts from 0.
```
>>> nums  = [ i for i in range(0,95) ]
>>> chars = [ chr((i+16) % 95 + 32) for i in nums ]
>>> index = [ (ord(c)+47) % 95 for c in chars ]
>>> nums
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, …
```
> Change egsphant format to allow up to 95 materials

- HEN_HOUSE/user_codes/egs_chamber/egs_chamber.cpp
- HEN_HOUSE/user_codes/egs_chamber/egs_chamber.macros
Fix the egs_chamber russian roulette splitting algorithm so that the latch variable is no longer used. Instead, an extra stack is created with a splitting variable in it. This avoids allowing egs_chamber to overwrite the latch, in case other objects such as `egs_phsp_scoring` need to use it.
Previously, if you used russian roulette in egs_chamber and scored a phsp using egs_phsp_scoring, the multiple passer flag for scoring particles may have been incorrect. I think this would be a small effect.
> Fix egs_chamber usage of latch for splitting

- HEN_HOUSE/egs++/geometry/egs_cylinders/egs_cylinders.h
Fixes the lone loop index compiler warning for egs++
> Fix loop index compiler warning in egs_cylinders/egs_cylinders.h

- HEN_HOUSE/scripts/configure
Use `wc -c` to obtain the number of bytes in the temporary file when determining the Fortran record length during EGSnrc configuration. The problem with `stat -c` is that it is not standard; for example, there is no `-c` option in BSD variants (macOS). Using the `stat` command is a regression introduced in issue #616 to remove a dependency on the format of the `ls` output.
> Fix command to get file size in configure script

- HEN_HOUSE/src/egsnrc.macros
- HEN_HOUSE/user_codes/g/g.mortran
This pull request addresses a bug in `g.mortran` in a type 1 calculation for multiple energies whereby the precision goal is reduced at every energy step potentially making the calculation last very long. Bug reported by @dworogers. 
Two other fixes are included in this pull request. See the list below for more information:
- For `calculation type 1` set desired uncertainty `accu0` at the first step of the energy loop. The value of `accu`
must be updated for each energy since it is different for the `mutr` and `1-g` calculation blocks. Fixes issue #665.
- Round-off errors produce wrong results for a 1 keV energy value. The quick fix is to add an epsilon equal to or larger than 1.0D-18 MeV. Using here a slightly larger epsilon of 1.0D-10 MeV to account for machine precision differences. …
> Fix bug in precision goal in g and 1 keV round-off

- HEN_HOUSE/pegs4/Makefile
- HEN_HOUSE/pegs4/pegs4.mortran
Since GNU gcc version 10.0 and up, `pegs4` compilation fails complaining about interface mismatch when using dummy arguments for functions. Previous versions (8.x and 9.x) used to report this only as warnings.
@joeydumont is credited with reporting this error and pointing to a solution based on `INTERFACE` blocks. This wasn't working due to Mortran interpreting `::` as empty labels.
The solution to the label issue is to use compiler directives `%M` and `%F` to switch between Fortran and Mortran code. Rather than using full INTERFACE blocks, the function type is included in the external statement for these functions. Subroutines are not affected.
A much simpler fix is to just add a type declaration statement for the dummy function arguments. Turns out @blakewalters  had already fixed this …
> Fix pegs4 compilation errors for gcc > 10.0

- HEN_HOUSE/egs++/egs_base_geometry.h
- HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.cpp
- HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.h
Fix the value of dose in 3ddose files generated from egs++ apps using `egs_dose_scoring`. The dose was not being scaled by the correct mass/density of materials, because the `getMass` function in the ND geometry was not functioning properly for XYZ geometries unless they were defined using an egsphant file or density file. In other words, the dose was wrong if the XYZ geometry boundaries were defined using "slabs" or "planes". 
This is a critical bug in the value of dose reported and has been an issue since the ability to generate 3ddose files was added to `egs_dose_scoring`. Any old dose in 3ddose files generated this way should be considered unreliable, due to the undefined value of density, and those simulations should be repeated.
Note that the doses reported by `egs_dose_scoring` by …
> Fix the dose values in egs++ 3ddose output

- HEN_HOUSE/src/EEMF_macros.mortran
- HEN_HOUSE/src/EEMF_macros_beamnrc.mortran
Fix a typo in the comments for EEMF, that made compilation fail. This must have a been a last-minute change that didn't get tested.
> Fix a typo that made EEMF fail to compile

- HEN_HOUSE/egs++/egs_base_geometry.cpp
- HEN_HOUSE/egs++/egs_functions.h
Reduce the value of the egs++ floating-point epsilon from 1e-10 to
a value that is 4 times (2 bits away) from the true machine epsilon, and
appropriately for single and double precision versions of the code.
Add a distanceEpsilon constant that is independent of the machine
epsilon, and much larger, but still entirely sufficient for physical
dimensions (well below atomic dimensions in double precision). By
default, the base geometry sets its boundaryTolerance to this
constant. Its value is close to the previous value of epsilon (1e-10),
which should curb any change in floating point error triggers in the
geometry library at this point.
Earlier in #177, the epsilon constant was introduced to remove
hard-coded floating point comparison guards. The 1e-10 value was chosen
because it matched …
> Reduce machine epsilon and add a distance epsilon

- HEN_HOUSE/omega/progs/gui/dosxyznrc/set_main_inputs_egsnrc.tcl
- HEN_HOUSE/omega/progs/gui/dosxyznrc/xyznrc_parameters.tcl
Fix the dosxyz_gui help text for phase-space output on exiting the phantom. I based the text on what is in the manual for the parameter. Previously, the help text for the `dsurround` parameter would show instead.
> Fix dosxyz_gui help text for phsp output

- HEN_HOUSE/egs++/sources/egs_beam_source/egs_beam_source.cpp
EGSnrc's work area can be changed to an arbitrary folder by redefining
`$EGS_HOME` on the command line (-e new_eh_path for interactive runs or
eh=new_eh_path for parallel runs). However, if an egs++ app uses a BEAM
source library, there was no way to reset `$EGS_HOME` for it.
Added the ability to redefine `$EGS_HOME` and `$HEN_HOUSE` for egs++
beam sources via the input block for an **EGS_BeamSource** object. Besides
entering the input file and pegs4 file names, one can now also use
```
:start source:
library = egs_beam_source
...
egs_home = new_eh_path/
hen_house = new_hh_path/
...
:stop source:
```
This is useful for working on arbitrary folders for different projects. In
this case a symbolic link to the `$EGS_HOME/bin` and `$EGS_HOME/pegs4` folders
will be required on the project …
> Set $EGS_HOME & $HEN_HOUSE for egs++ beam sources

- HEN_HOUSE/egs++/Makefile
- HEN_HOUSE/egs++/shapes/egs_circle_perpendicular/Makefile
- HEN_HOUSE/egs++/shapes/egs_circle_perpendicular/egs_circle_perpendicular.cpp
- HEN_HOUSE/egs++/shapes/egs_circle_perpendicular/egs_circle_perpendicular.h
Adds a new circle shape where the angle of the surface of the circle depends on the position of the source particle directed toward it.
This shape is specified via
```
:start shape:
library = egs_circle_perpendicular
radius = the circle radius
midpoint = Ox, Oy (optional)
inner radius = the inner radius (optional)
:stop shape:
```
and delivers points uniformly distributed within a circle. The surface of this circle is always perpendicular to a ray based on the source particle position, when this shape is used as the target in a source that calls the `getPointSourceDirection()` function. For example, in a collimated source when a source shape and target shape are defined, the special properties of this circle only apply when it is used as the target shape. Otherwise, it behaves like an …
> Add egs_circle_perpendicular shape

- .github/CODEOWNERS
Add the team @nrc-cnrc/egsnrc as the code owner for all files in the repository, so reviews by members of that team will automatically be requested. In time, code owners can be added, expecially for external contributions, so that the original authors can be notified and review changes to their code. The file is added inside the `EGSnrc/.github` directory.
> Add code owners file to automate review requests

- HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
Photons were not included in the phase space data.  This is because $AUSCALL($TRANAUSA) (call to ausgab after particle step) was not included in the $SELECT-PHOTON-MFP macro that handles splitting in dosxyznrc.
> Fix phsp output with photon splitting

- HEN_HOUSE/user_codes/g/g.mortran
g app crashes when used for a spectrum due to a superfluous command left
in entry point `source_check_emin` copied from entry `point source_get_emax` 
during implementation of the former.
Thanks to @dworogers for reporting this bug.
> Fix g bug: SEGFAULT when using spectrum

- HEN_HOUSE/user_codes/tutor7pp/tutor7pp.cpp
Before this change, there was a small risk of buffer overflow in the
tutor7pp fluence scoring arrays. The value r2 was checked to be less
than 400, and then the scoring bin number (from 0 to 199) is calculated
using the expression `(int)(sqrt(r2)*10.)`. The problem with this check
is that certain double precision values less than 400 can nevertheless
have a square root equal to exactly 20.0 due to floating-point rounding.
For example, taking the square root of the double 399.99999999999994
results in 20.0 under certain conditions, not a value slightly less than
20.0 as would be expected. The default g++ rounding mode is
round-to-nearest, so even with the square root's true value being under
20.0, the resulting double can be rounded upwards to 20.0 if the true
value is closer to 20.0 than …
> Fix buffer overflow from scoring bin rounding

- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.h
Before this change, there was an out-of-bounds read in d_reg_index when `ir` was -1. Fixes #828.
> Check that ir is not -1 for region dose scoring

- HEN_HOUSE/doc/src/pirs898-egs++/common.doxy
- HEN_HOUSE/interface/egs_interface2.h
> Document NRC brems cross section option

- HEN_HOUSE/src/egsnrc.mortran
**Unexpected behavior:** Results depend on the order in which the material
composition is defined. This is clearly a bug as  elements can be entered in 
an arbitrary order to define compounds and mixtures.
**Reported by:** Iymad Mansour (issue #844) who observed that `egs_brachy` simulations of
an irradiation with an isotropic 35 keV photon point source embedded
in a steel applicator, produced 5% differences in the surface dose of
a water phantom when the order of the steel components was changed.
Confirmed with `egs_kerma` for a 35 keV photon point source surrounded by
a 1 mm steel encapsulation embedded in a spherical water phantom. Kerma
at the spherical water shell next to the encapsulation differs by 4%.
**BUG:** Sampling element and atomic shell for photo-electric interaction
with …
> Fix serious bug in MCDF-XCOM PE routine

- HEN_HOUSE/scripts/egs-parallel-pbs
- HEN_HOUSE/scripts/egs-parallel-pbsdsh
Fix a mistake in the previous fix for non-alphanumeric characters in the job name in egs-parallel jobs resulting in a crash. The previous fix removed non-alphanum characters from the start of the original job name, but actually we needed to remove from the start of the trimmed 14 character job name.
> Fix egs-parallel job name with invalid leading character bug

- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.cpp
This resolves #708. At the same time I have realigned the output slightly. While not perfect in regards to all cases, I find it provides a better default alignment. Sample output:
```
==> Summary of region dosimetry (per particle)
ir  medium  rho (g/cm^3)  Volume (cm^3)   Edep (MeV)                   D (Gy)                   
------------------------------------------------------------------------------------------------
0  air      0.00120479  270000.000000    1.7576e-02  +/-  0.697  %    8.6558e-15  +/-  0.697  %
1  water    1.00000000     100.000000    1.9265e+00  +/-  0.262  %    3.0862e-12  +/-  0.262  %
2  air      0.00120479     900.000000    6.9888e-02  +/-  0.496  %    1.0326e-11  +/-  0.496  %
--------------------------------------------------------------------------------------- …
```
> Increase floating point-precision for rho output in dose scoring object

- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.cpp
- HEN_HOUSE/egs++/egs_scoring.h
Change a few occurances of `endl` to `\n` in egs++ mid-simulation scoring routines, to increase performance. The reason for this is that `endl` performs a buffer flush each time, which I believe is not necessary. The takeaway here is to never use `<< endl` unless you actually want the flush.
The performance hit was huge for large arrays, like a 300x300x300 3ddose file. On linux this was a 50% speedup on the total simulation time, on windows 400%. For smaller scoring arrays (i.e. most cases) the speedup will be minimal.
There is an outstanding problem that even with these changes, egs++ simulations with large 3ddose files are many times slower than dosxyznrc (2-30x slower), entirely due to the storeState function. This might be fixed if we remove ostream and use fprintf instead, but that …
> Change endl to \n in egs++ scoring to improve performance

- HEN_HOUSE/egs++/egs_application.cpp
As discussed in https://github.com/nrc-cnrc/EGSnrc/issues/745, ensure that multiple `EGS_TrackScoring` objects are not defined as this can lead to bugs at write time when the objects try to write to the same file (i.e. if the `file name addition` is blank). More than one track scoring object is not seen as a required feature, since photons, electrons and positrons can all be toggled in `egs_view`.
```
:start ausgab object:
library = egs_track_scoring
name    = some_name
score photons   = yes or no # optional, yes assumed if missing
score electrons = yes or no # optional, yes assumed if missing
score positrons = yes or no # optional, yes assumed if missing
start scoring   = event_number # optional, 0 assumed if missing
stop  scoring   = event_number # optional, 1024 assumed if missing …
```
> Guard against more than one track_scoring object in egsinp

- HEN_HOUSE/egs++/view/image_window.cpp
After compiling `egs_view` with asan support, there was a buffer overflow
error encountered opening `tutor7pp/test1.egsinp`.
It was traced back to the memcpy call in `ImageWindow::paintEvent`:
```
==26122==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7ffe71889e40 at pc 0x7f543595ece0 bp 0x7ffe71889da0 sp 0x7ffe71889548
READ of size 400 at 0x7ffe71889e40 thread T0
#0 0x7f543595ecdf  (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x99cdf)
#1 0x55dc3acdbb15 in memcpy /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34
#2 0x55dc3acdbb15 in ImageWindow::paintEvent(QPaintEvent*) /home/max/projects/EGSnrc/HEN_HOUSE/egs++/view/image_window.cpp:348
#3 0x7f5434f86047 in QWidget::event(QEvent*) (/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x193047)
```
The issue is that memcpy …
> Fix out-of-bounds read in `egs_view` by making region arrays the same size

- HEN_HOUSE/doc/src/getting-started/getting-started.tex
In the solution to one of the questions in the getting-started manual, the total dose was calculated as the sum of dose to regions, instead of appropriately weighted by the relative volume of each region. This was corrected, as well as another typo in the instructions.
Thanks to @mjukdisk for reporting this (https://github.com/nrc-cnrc/EGSnrc/discussions/780).
> Fix a mistake in the getting-started solutions

- HEN_HOUSE/doc/src/pirs898-egs++/common.doxy
Add documentation for the `rng definition` block in egsinp files. Will have to be adjusted if `high resolution = yes` becomes the default (https://github.com/nrc-cnrc/EGSnrc/issues/594).
Rendered:
> Document egs++ rng definition block

- HEN_HOUSE/omega/progs/gui/beamnrc/syncjaws.tcl
Fix #803 a GUI error that occurred in DYNJAWS jaw definitions when clicking
the button to calculate the jaw settings from the field size and SSD.
The button triggered a function that was duplicated with the same name
in SYNCJAWS, leading to the error. As the fix, the syncjaws version of
the function has been renamed. This bug has existed since SYNCJAWS was
added to the GUI.
> Fix #803 a quiksyncdef error from DYNJAWS in BEAMnrc GUI

- HEN_HOUSE/omega/progs/addphsp/addphsp.mortran
For EGSnrc format phsp if total no. of particles in header > 2^32-1.
Addresses Issue #724.
> Add check for maximum number of particles to addphsp

- HEN_HOUSE/omega/progs/ctcreate/ReadCT_DICOM.c
As outlined in issue #718, `ReadCT_DICOM()` currently works only with slices of size 512-by-512. This is a quick fix to make it work with smaller sizes as well.
> Fix `ReadCT_DICOM()` to work with slices of arbitrary size

- HEN_HOUSE/egs++/view/view.pro
- HEN_HOUSE/gui/egs_configure/egs_tools.cpp
- HEN_HOUSE/scripts/configure_c++
The `egs_view` gui already specifies c++11, and the new mesh geometry also requires c++11. These changes are extracted from #637 to create a distinct commit, and updated to c++14 while we are at it.
> Update compiler flags to require c++14 standard

- HEN_HOUSE/egs++/view/view.pro
- HEN_HOUSE/gui/egs_configure/egs_tools.cpp
- HEN_HOUSE/scripts/configure_c++
Add checks to the configure script, configuration GUI, and egs_view profile before setting `std=c++14` as the default c++ standard. If the gcc version is 4 or less, then `std=c++11` is used as the default. This just helps protect against failed installations for users with older gcc versions using the default config settings.
Very old versions of gcc might still crash, but the user can easily change the `std=` flag as necessary.
> Add checks for gcc version when setting the default c++ standard

- HEN_HOUSE/gui/egs_configure/egs_install.h
- HEN_HOUSE/makefiles/cpp_makefile
- HEN_HOUSE/makefiles/standard_makefile
- HEN_HOUSE/specs/all_common.spec
- HEN_HOUSE/src/egs_utilities.mortran
Fix an issue with long branch names where the fortran code would fail to compile because of exceeding the line length. This isn't completely fixed, but now a few more characters are allowed before it crashes. Correct me if I'm wrong, but I think it's not possible to fix completely, because it seems like the DEFINE replacement means that we can't use mortrans usual automatic line wrapping.
Fix the comparisons between egs_home and HEN_HOUSE/user_code applications, so that it doesn't report a difference when the HEN_HOUSE version doesn't exist to start with.
This fixes minor issues introduced in PR #414.
> Fix git branch logging and egs_home vs HEN_HOUSE code comparisons

- HEN_HOUSE/egs++/sources/egs_radionuclide_source/egs_radionuclide_source.cpp
- HEN_HOUSE/egs++/sources/egs_radionuclide_source/egs_radionuclide_source.h
This pull request replaces #672. The original pull request branch was removed from the forked repository, so the branch and pull request is hereby reinstated. The original pull request message was:
> The implementation of `egs_radionuclude_source` is changed so that it takes an input "base source" instead of defining a collimated or isotropic source. This way you can use any of the egs sources or a custom egs source to define the location of the radionuclide in the simulation. The change in particular was made towards fast simulations targeted radionuclide therapy across a whole patient phantom.
> Use position/direction sampling from base source for radionuclide sources

- HEN_HOUSE/scripts/configure
- HEN_HOUSE/scripts/configure_c++
Add tests in the configure scripts to avoid setting the gcc memory model flag `-mdmodel=medium` if a darwin (macOS) system is detected. This flag causes compilation failures at the linking stage.
> Fix #904: avoid gcc -mcmodel flag on macos systems

- HEN_HOUSE/doc/src/pirs794-dosxyznrc/inputs/dosxyznrc.inp
- HEN_HOUSE/doc/src/pirs794-dosxyznrc/pirs794-dosxyznrc.tex
- HEN_HOUSE/omega/progs/gui/dosxyznrc/create_file_nrc.tcl
- HEN_HOUSE/omega/progs/gui/dosxyznrc/load_input2_nrc.tcl
- HEN_HOUSE/omega/progs/gui/dosxyznrc/reset_parameters_nrc.tcl
- HEN_HOUSE/omega/progs/gui/dosxyznrc/set_main_inputs_egsnrc.tcl
- HEN_HOUSE/omega/progs/gui/dosxyznrc/xyznrc_parameters.tcl
- HEN_HOUSE/src/egs_utilities.mortran
- HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
Just throwing this pull request up here to see if there is any interest. It was a fairly simple change to make.
As part of my research, I use DOSXYZnrc to generate electron beamlets for mixed electron-photon optimisation. A full set of electron beamlets for 5 gantry angles for a single chest wall patient (15,000 beamlets total) with 3mm^3 voxels takes up 2.1 TB of disk space when they're stored as 3ddose files. Just the process of converting beamlets to a nicer format takes a long time. When stored as sparse binary files, the same set of beamlets takes ~14 GB. Being able to output directly to binary dose saves tons of space and time.
The format is similar the 3ddose format, except that voxels with 0 dose are omitted. The binary file is constructed as:
- x_num_voxels, y_num_voxels, …
> Option: output sparse binary dose file instead of 3ddose in DOSXYZnrc

- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.cpp
- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.h
- HEN_HOUSE/egs++/egs_advanced_application.cpp
- HEN_HOUSE/egs++/egs_base_geometry.h
- HEN_HOUSE/egs++/geometry/egs_autoenvelope/egs_autoenvelope.cpp
- HEN_HOUSE/egs++/geometry/egs_autoenvelope/egs_autoenvelope.h
- HEN_HOUSE/egs++/geometry/egs_autoenvelope/volcor.h
- HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.cpp
- HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.h
- HEN_HOUSE/egs++/geometry/egs_rz/egs_rz.cpp
- HEN_HOUSE/egs++/geometry/egs_rz/egs_rz.h
- HEN_HOUSE/egs++/geometry/egs_spheres/egs_spheres.cpp
- HEN_HOUSE/egs++/geometry/egs_spheres/egs_spheres.h
The egs_base_geometry getMass virtual function is exchanged with
a getVolume function that returns region volume instead of mass.
This change was performed because typically, initGeometry() is
invoked before any media data is read in egs_applications, thus
getMass' dependence on medium data could be unreliable.  The
getMass function was thus replaced with a getVolume function,
which only relies on internal gemoetry definitions to return a
value.
The geometries in egs_autoenvelope, egs_nd_geometry, egs_rz,
and egs_spheres are affected.  The ausgab dose scoring object
which outputs a 3ddose file was also changed to reflect the
change from getMass to getVolume.  This modification of
egs_dose_scoring also now includes relativeRho in the mass
calculation.
> Fix egs++ 3ddose output and change getMass to getVolume

- HEN_HOUSE/makefiles/beam_makefile
- HEN_HOUSE/specs/beamnrc.spec
- HEN_HOUSE/src/egs_utilities.mortran
Fix compilation failure of BEAMnrc accelerators since the addition of git has logging and compile time logging in PR #414. 
This also adds back printing of the git hash, which was mistakenly removed in PR #898.
> Fix logging of git hash and compile time for BEAMnrc

- HEN_HOUSE/scripts/configure_c++
g++ compiler may have a longer name (e.g., g++-11) and the wrong variable was being printed in options.
> Fix configure_c++ on macOS

- HEN_HOUSE/omega/progs/ctcreate/ctcreate.mortran
- HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
- HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc_user_macros.mortran
Revert to the `egs_brachy` encoding for `.egsphant` files, allowing for 63 media encoded with the set of alphanumeric characters (where 0 is reserved for vacuum).
Briefly, #633 expanded the number of media in `.egsphant` files to 95, using all printable ascii characters. However, the number of media was also independently expanded in `egs_glib` for the development of `egs_brachy`, but using a different encoding consisting of only the 63 alphanumeric ascii characters. This leads to inconsistent egsphant files that are no longer interchangeable.
This issue was originally reported and discussed in https://github.com/clrp-code/egs_brachy/issues/22.
> Fix #894: revert egsphant to egs_brachy encoding

- .gitmodules
- third-party/README.md
This pull request supersedes #632. The idea is to include the 3ddose_tools as a submodule in `EGSnrc/third-party/`, instead of including the source code itself within EGSnrc.
A submodule provides a way to include a git repository _within_ another repository. This way, the submodule authors keep full control of their code development (and user support!) for the third-party software. In fact, EGSnrc is not distributing the software code at this point, but merely a reference to it. This means that developers can even distribute their code under different conditions, e.g., a different licence. This provides exposure as part of the EGSnrc project, and eventually the ability to synchronize the version of third-party content with each EGSnrc release.
When EGSnrc is cloned, submodule content is …
> Add 3ddose_tools as a third-party submodule

- HEN_HOUSE/user_codes/egs_chamber/example1_co60_Pfactors.egsinp
- HEN_HOUSE/user_codes/egs_chamber/example1_profile_pfactors.egsinp
- HEN_HOUSE/user_codes/egs_chamber/example2_chamber_dd.egsinp
Fix the egs_chamber examples so that they now run without needing to compile any BEAMnrc accelerators or make changes to the input file. Also fix a typo in the example2 water box size.
> Fix #945, #804: egs_chamber examples don't run by default

- HEN_HOUSE/doc/src/pirs898-egs++/Doxyfile
- HEN_HOUSE/doc/src/pirs898-egs++/aobjects.doxy
- HEN_HOUSE/doc/src/pirs898-egs++/main.doxy
- HEN_HOUSE/egs++/Makefile
- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/Makefile
- HEN_HOUSE/egs++/ausgab_objects/egs_fluence_scoring/Makefile
- HEN_HOUSE/egs++/ausgab_objects/egs_fluence_scoring/egs_fluence_scoring.cpp
- HEN_HOUSE/egs++/ausgab_objects/egs_fluence_scoring/egs_fluence_scoring.h
- HEN_HOUSE/egs++/egs_advanced_application.cpp
- HEN_HOUSE/egs++/egs_advanced_application.h
- HEN_HOUSE/egs++/egs_application.h
- HEN_HOUSE/egs++/egs_base_source.h
- HEN_HOUSE/egs++/egs_interpolator.cpp
Scores fluence in _user-defined_ regions (`volumetric`) or at a circular or rectangular field (`planar`) located in an arbitrary position in space. Scoring can be done for either photons, electrons or positrons. Scoring for multiple particle types, can be accomplished by defining as many fluence scoring AOs as required.
> A generic fluence scoring ausgab object (AO)

- HEN_HOUSE/egs++/geometry/egs_mesh/egs_mesh.h
Fix a missing include of the `array` class library in egs_mesh.h. This avoids compiler errors that occurred on mac.
> Fix #949: compiler errors of egs_mesh on mac

- HEN_HOUSE/omega/beamnrc/beamnrc.mortran
- HEN_HOUSE/user_codes/cavrznrc/cavrznrc.mortran
- HEN_HOUSE/user_codes/cavsphnrc/cavsphnrc.mortran
- HEN_HOUSE/user_codes/dosrznrc/dosrznrc.mortran
- HEN_HOUSE/user_codes/egs_chamber/egs_chamber.cpp
- HEN_HOUSE/user_codes/flurznrc/flurznrc.mortran
- HEN_HOUSE/user_codes/sprrznrc/sprrznrc.mortran
Add ausgab calls before and after a photonuclear interactions, in order to handle cross section enhancement (xcse) correctly. Without these calls, there is no compensation for the enhanced cross section, hence the photonuclear cross section is effectively increased.
Also, update a couple loops that print out the ausgab flags (IAUSFL) values, to include the photonuclear attenuation input value, and fix a couple typos.
> Fix photonuclear cross section biasing when using cross section enhancement

- HEN_HOUSE/user_codes/egs_cbct/egs_cbct.cpp
- HEN_HOUSE/user_codes/egs_cbct/example_w5br.egsinp
- HEN_HOUSE/user_codes/egs_fac/egs_fac.cpp
Fix a compiler error that occurred with newer compiler settings due to ambiguous declaration of isinf and isnan, by adding `std::`.  
Also change the z-rotation parameter in the example input file to be 0 so that it calculates the first projection instead of a later projection. This avoids a common user error when trying to produce the blank scan for the first time, as reported here: https://www.reddit.com/r/EGSnrc/comments/z36841/query_fatal_error_message_egs_cbct_blank_scan/
> Fix egs_cbct, egs_fac compilation and egs_cbct example

- HEN_HOUSE/user_codes/egs_cbct/egs_cbct.cpp
- HEN_HOUSE/user_codes/egs_cbct/example_w5br.egsinp
- HEN_HOUSE/user_codes/egs_fac/egs_fac.cpp
Add a single commit from `develop` to resolve compilation errors on v2023
> Fix egs_cbct and egs_fac compilation errors for v2023 release

- HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.cpp
This is a cherry pick from #1011 to fix the ausgab object formatting, which was messed up because a line removed in 35a59d36.
> Fix formatting issues in dose scoring ausgab object

- index.md
This is the same as #976, but for the webpage located on the `gh-pages` branch.
> Update repo webpage to remove reddit link

- HEN_HOUSE/gui/egs_configure/egs_tools.cpp
- HEN_HOUSE/scripts/configure
- HEN_HOUSE/specs/all_common.spec
- HEN_HOUSE/specs/beamnrc.spec
1. Fix a bug where applications would fail to compile on windows in locations where the time zone was a long string. This was due to the COMPILE_TIME flag that included some text about the time zone. To fix the issue, the time zone was removed from the variable and output.
2. Fix an issue where lquadmath was not included with lgfortran, and the compiler would fail on some systems. 
3. Fix a compiler error that occurred when the user had installed git, but then installed EGSnrc using the zip file. Users would see an error about GIT_HASH not being defined in this case.
4. Fix a minor warning that was printed about it not being a git repository.
@ftessier please check that the lquadmath changes don't cause any issues on OS X. I recommend that we cherry pick these fixes into v2023.
> Fix compilation on windows for some time zones, add lquadmath

- HEN_HOUSE/src/egsnrc.mortran
Clarify that multiple-scattering transport is triggered only if the intended electron step is longer than a skin depth, even in bulk media away from any region boundaries. This improves efficiency, because a multiple-scattering step costs about the same as 3 single-scattering steps (the default skin depth is 3 mean free paths). Below a skin depth, it is more efficient (and more accurate) to use single-scattering.
> Fix #1131: clarify comment about ms conditional

- HEN_HOUSE/omega/beamnrc/beamnrc.mortran
Fix the output message in the egslst file for BEAMnrc simulations about the number of brems events the took place. When DBS was turned on, it would always read zero.
Just to be clear, there was nothing wrong with the splitting or the simulation. This is just a small bug in the counter variable that is only used to print to the egslst file.
@blakewalters please double check this change.
> Fix #1018: Number of brems events miscounted for DBS in BEAMnrc

- HEN_HOUSE/egs++/ausgab_objects/egs_phsp_scoring/egs_phsp_scoring.cpp
Fix a bug in egs_phsp_scoring where the electron (and positron) energy for IAEA phase-spaces was written as the total energy instead of the kinetic energy. This is a critical bug and impacted all IAEA format phase-spaces generated from egs++ that contained charged particles.
Thanks to Erik Nilsson for reporting this issue!
> Fix egs++ iaea phsp scoring electron energy

- HEN_HOUSE/egs++/sources/egs_source_collection/egs_source_collection.cpp
- HEN_HOUSE/egs++/sources/egs_source_collection/egs_source_collection.h
Fluence for the source collection was not calculated properly in the case of a collection consisting of N transformations, i, of a single base source.  EGS_SourceCollection::getFluence() sums the results of getFluence() for the i individual sources.  If they are transformations of a single base source, then for each source i, getFluence returns the total fluence (of the base source), F_tot.  Thus, EGS_SourceCollection::getFluence() erroneously returns N*F_tot.  
The solution is to "detect" a group of sources sharing a common base source by looking for increases in the fluence of source i != j, where j is the source in the collection from which a given particle is being sampled.  Before summing individual source fluences, EGS_SourceCollection::getFluence() then multiplies the result of …
> Fix #1065: source collection fluence

- HEN_HOUSE/egs++/egs_application.cpp
- HEN_HOUSE/egs++/egs_application.h
- HEN_HOUSE/egs++/egs_base_source.h
- HEN_HOUSE/egs++/egs_run_control.cpp
- HEN_HOUSE/egs++/sources/egs_dynamic_source/egs_dynamic_source.h
- HEN_HOUSE/egs++/sources/egs_phsp_source/egs_phsp_source.cpp
- HEN_HOUSE/egs++/sources/egs_phsp_source/egs_phsp_source.h
- HEN_HOUSE/egs++/sources/egs_source_collection/egs_source_collection.h
- HEN_HOUSE/egs++/sources/egs_transformed_source/egs_transformed_source.h
- HEN_HOUSE/egs++/sources/iaea_phsp_source/iaea_phsp_source.cpp
- HEN_HOUSE/egs++/sources/iaea_phsp_source/iaea_phsp_source.h
This fix divides phase space sources used in parallel runs into npar\*nchunk equal segments, where npar is the no. of parallel runs and nchunk is the no. of chunks (defaults to 10).  Each chunk of the parallel run is then assigned its own segment of the phase space source outside of which it will not sample.  This scheme, identical to that used in the Mortran codes, should ensure relatively even sampling of the phase space source over the entire parallel run.  Note that any remaining histories after completion of npar*nchunk chunks are assigned to the last segment. 
Fixes issue #1117 and #1156
> Fix parallel phsp source partition

- HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.h
Fix bug in EGS_XYZRepeater hownear
- Typo in hownear when particle in bounding box determining which of
the repeated geometries to check:
Using nz rather than nxy when computing index of repeated geometry array
results in addressing array index out of bounds with subsequent segfault error.
Showed when eletron transport turned ON up during dose calculations around
a CivaDot source using egs_dose_scoring and egs_app and 2 microns regions.
It did not affect photon-only nor egs_kerma calculations since there is no
call to hownear. ;-)
> Fix egs xyzrepeater bug

- HEN_HOUSE/egs++/shapes/egs_circle_perpendicular/egs_circle_perpendicular.h
Fix a bug in `egs_circle_perpendicular` that made the geometry invalid for any cases where the circle was expected to face away from the z-axis. Anyone who used this geometry should check their results.
This bug persisted because testing was done on a version where a similar fix had been done, but never included in the distribution. 
Example that incorrectly produced a line target instead of a circle:
```
:start source:
library = egs_collimated_source
name = isotropic_collimated_source
:start source shape:
type = point
position =  900 0.000000 0.000000
:stop source shape:
:start target shape:
library = egs_circle_perpendicular
midpoint = 0 0
radius = 25
:stop target shape:
charge = 0
:start spectrum:
type = monoenergetic
energy = 2
:stop spectrum:
:stop source:
```
> Fix egs_circle_perpendicular critical bug

- HEN_HOUSE/egs++/ausgab_objects/egs_fluence_scoring/egs_fluence_scoring.h
- HEN_HOUSE/egs++/ausgab_objects/egs_radiative_splitting/egs_radiative_splitting.cpp
- HEN_HOUSE/egs++/ausgab_objects/egs_radiative_splitting/egs_radiative_splitting.h
- HEN_HOUSE/egs++/egs_advanced_application.cpp
- HEN_HOUSE/egs++/egs_advanced_application.h
- HEN_HOUSE/egs++/egs_application.h
Initial radiative splitting implementation naively just turned ON EGSnrc internal flag `nbr_split` to split brems and annihilation events uniformly. However no charged particle RR was played after pair production (`i_play_RR`) nor were secondary photons, produced by charged particles surviving RR after bremsstrahlung, split.
This PR fixes issue #1001
Implement radiative splitting + RR
--------------------------------------
- Now turned ON before a radiative event for a primary or a fat charged particle. 
Turned OFF after the event to avoid higher order splitting. Fluorescent fat photons, 
generated by fat charged particles (survived RR) are also split.
- RR is turned ON using EGSnrc internal flag `i_play_RR` so that RR is played after pair events. 
RR can be turned OFF by entering a …
> Fix radiative splitting ao

- HEN_HOUSE/doc/src/pirs3100-g-app/g_template.f
- HEN_HOUSE/egs++/ausgab_objects/egs_fluence_scoring/egs_fluence_scoring.cpp
- HEN_HOUSE/omega/progs/beamdp/beamdp.mortran
- HEN_HOUSE/src/get_media_inputs.mortran
- HEN_HOUSE/user_codes/cavity/cavity.cpp
- HEN_HOUSE/user_codes/edknrc/edknrc.mortran
- HEN_HOUSE/user_codes/egs_kerma/egs_kerma.cpp
- HEN_HOUSE/user_codes/examin/examin.mortran
- HEN_HOUSE/user_codes/sprrznrc/sprrznrc.mortran
Addresses #1004.
Note: I find our method for specifying axis units in beamdp using a backslash in front of the unit (i.e., '/unit') confusing, especially for quantities which may also have a unit in the denominator (e.g., '/MeV cm^-2').  I wonder if we should move to just using brackets instead.
> Fix #1004: beamdp axis labels are confusing

- HEN_HOUSE/scripts/config.guess
- HEN_HOUSE/scripts/configure
- HEN_HOUSE/scripts/configure_c++
This adds support for building on Linux aarch64
I was specifically testing in Docker on MacOS with Apple Silicon. I tested with Debian and Ubuntu base images.
* [`HEN_HOUSE/scripts/config.guess`](diffhunk://#diff-8eb1825d07f152323a716762643133f58e783dff2708dbe0394743e7a20da225R833-R835): Added a new case for `aarch64` in the Linux environment to return the machine type as `aarch64-unknown-linux-gnu`.
* [`HEN_HOUSE/scripts/configure`](diffhunk://#diff-1fcddaf8748e652b20e5ac55635f6908417fe57d57dc0cca699fa2f1df7fe822R136-R138): Set the `memory_model` to an empty string if the `canonical_system` is `aarch64`.
* [`HEN_HOUSE/scripts/configure_c++`](diffhunk://#diff-26bdc3f68325c49956643e7ea0f4de41040771e60c11cd9c8420ef9508d2b8cfR171-R173): Set the `memory_model` to an empty string if the …
> Add support for Linux aarch64 architecture (ARM)

- .devcontainer/README.md
- .devcontainer/build-gui-apps.sh
- .devcontainer/devcontainer.json
- .devcontainer/setup.sh
- .gitignore
This adds the configuration necessary to build and run EGSnrc in a Development Container. I have
successfully tested this in the following environments:
Documentation:
* [`.devcontainer/README.md`](diffhunk://#diff-0f9548cbce10dbdef0b86d783ed0727a4ac1061fc71cb549b5dbd400705c71fdR1-R92): A new README file has been added to explain how to use the development container. It provides instructions for different environments and addresses potential issues, such as line-endings in files when running locally on Windows. It also describes the runtime experience and provides reference information.
Development container configuration:
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686R1-R19): This file contains the configuration for …
> Configuration and documentation for building and running in Codespaces or Development Container

- HEN_HOUSE/makefiles/beam_makefile
- HEN_HOUSE/omega/beamnrc/beamnrc.mortran
BUG: Commit 8023cd01 labels fluorescent photons after EII as secondary.
The pertinent block for UBS and/or BCSE requires knowledge of the local
region number IRL, which is only set later in AUSGAB.
FIX: Set IRL above the UBS/BCSE block in the AUSGAB routine.
This PR also adds the libclean target to the standard BEAMnrc Makefile.
> Fix bug in UBS/BCSE EII photon splitting block in BEAMnrc

- HEN_HOUSE/egs++/ausgab_objects/egs_fluence_scoring/egs_fluence_scoring.cpp
- HEN_HOUSE/user_codes/cavity/cavity.cpp
Revert changes to units in the output of egs_fluence_scoring and cavity. The units were already correct before the change, because the C++ compilers interpreted the escaping differently than the fortran compilers.
This fix was also needed to avoid compiler errors when using newer compilers. Due to this, recent installation of the `develop` branch would not work on gcc-13.
> Fix fluence label compiler error caused by PR #1170

- HEN_HOUSE/egs++/egs_particle_track.h
Add support for gcc 4.8.5 in recent changes added with the dynamic geometry and dynamic track scoring. This just fixes a compiler error due to initializing a char array in a constructor.
> Fix dynamic track compilation on old compilers

- HEN_HOUSE/user_codes/egs_kerma/egs_kerma.cpp
- HEN_HOUSE/user_codes/egs_kerma/example_20MeV_e-_Pb-shield_FD.egsinp
- HEN_HOUSE/user_codes/egs_kerma/example_40keV_SDD_1m_FD.egsinp
- HEN_HOUSE/user_codes/egs_kerma/example_5keV_H2O_FD.egsinp
- Fixes diff fluence normalization to proper bin width when using log-scale.
- Fixes bug printing out average source energies and number of particles to egsdat file causing combining parallel jobs to fail.
- Fixes bug introduced to preserve latch and only multiply it by -1 when entering an exclusion region. Now photon is killed rather than relying on latch. Speeds up example calculation `example_1m_40keV_FD.egsinp` by 40 %
- Veryfies that scoring regions are not define as exclusion regions.
The latch of particles was reset to 0 and now is accepted as it comes from the source. This can be useful for VRT AOs such as radiative splitting.
| Case      | Kerma / Gy/particle | wall contribution| histories / h |
| ----------- | ----------- |---|---|
| latch = -1      |   3.530745e-18 +/- 0.0074 …
> Fix egs kerma diff flu ouput for log-scale

- HEN_HOUSE/utils/srcrz.mortran
Fix a critical bug in the RZ codes when using IAEA phase-space sources. All particles from the phase-space were assigned to be photons, due to a missing initialisation of some phase-space related variables. This bug affects all RZ code simulations using IAEA phase-space sources with particles other than photons. I believe the bug has existed since earlier than 2015.
Big thanks to @yamane89 for reporting the issue: https://github.com/nrc-cnrc/EGSnrc/issues/1253
> Fix #1253: RZ codes IAEA phase-space particle charge not used

- HEN_HOUSE/utils/srcrz.mortran
Fix missing initialization of variables for IAEA phase-spaces in the RZ codes. While this didn't result in a crash, it did result in a bug where all particles were assigned a charge of 0 during the transport.
> Fix #1253: missing RZ iaea phsp macros
