HEN_HOUSE/egs++/ausgab_objects/egs_dose_scoring/egs_dose_scoring.cpp
HEN_HOUSE/egs++/shapes/egs_shape_collection/egs_shape_collection.cpp
HEN_HOUSE/omega/progs/gui/beamnrc/pegsless_egsnrc.tcl

Fixes a segfault when less than two shapes are defined for a shape collection.

fix format specifier for shape collection warning (currently segfaults)

---

HEN_HOUSE/src/egs_utilities.mortran
HEN_HOUSE/src/get_media_inputs.mortran

Feature pegsless fix plus

---

HEN_HOUSE/egs++/geometry/egs_cd_geometry/egs_cd_geometry.h

Fix bug in CD geometry

---

HEN_HOUSE/egs++/geometry/egs_cd_geometry/egs_cd_geometry.h

Revert "Fix bug in CD geometry"

---

HEN_HOUSE/doc/src/pirs509a-beamnrc/pirs509a-beamnrc.tex
HEN_HOUSE/doc/src/pirs701-egsnrc/inputs/chapter2_2.tex
HEN_HOUSE/doc/src/pirs701-egsnrc/inputs/new_um_app2.tex
HEN_HOUSE/doc/src/pirs701-egsnrc/inputs/pegsless_um.tex
HEN_HOUSE/doc/src/pirs702-egsnrc-codes/pirs702-egsnrc-codes.tex

Made it more clear and concise.

Fix pegsless documentation

---

HEN_HOUSE/doc/src/pirs701-egsnrc/inputs/chapter2_2.tex

This is different depending on the application type. This addresses issue #154 .

Add more detail about enabling radiative Compton corrections

---

HEN_HOUSE/doc/src/pirs794-dosxyznrc/pirs794-dosxyznrc.tex
HEN_HOUSE/omega/progs/gui/dosxyznrc/create_file_nrc.tcl
HEN_HOUSE/omega/progs/gui/dosxyznrc/load_input2_nrc.tcl
HEN_HOUSE/omega/progs/gui/dosxyznrc/reset_parameters_nrc.tcl
HEN_HOUSE/omega/progs/gui/dosxyznrc/set_source.tcl
HEN_HOUSE/omega/progs/gui/dosxyznrc/xyznrc_parameters.tcl
HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.macros
HEN_HOUSE/user_codes/dosxyznrc/srcxyznrc.mortran

Follows from #210, but @blakewalters added the option in the DOSXYZnrc gui and documented it in the manual.

Add option to skip DOSXYZnrc source 20 calibration

---

README.md

Avoids duplication of text by referencing the wiki for installation.

Update the readme text

---

HEN_HOUSE/doc/src/pirs898-egs++/customdoxygen.css
HEN_HOUSE/doc/src/pirs898-egs++/header.html
HEN_HOUSE/doc/src/pirs898-egs++/main.doxy

The image scroller is now on display in the header of the pirs898 class library, and shuffles randomly through a series of images.

Add image scroller to pirs898 header

---

HEN_HOUSE/interface/egs_c_interface1.macros
HEN_HOUSE/interface/egs_c_interface2.macros

Issue #260 has pointed out that out rest mass fix yesterday didn't work for cpp applications. Here is a fix.

Fix #260: rest mass declarations in C interface

---

HEN_HOUSE/egs++/egs_spectra.cpp

Add the option to discard radionuclide alpha particles (the default) or include them as a local energy deposition. The is done using the `alpha scoring` input option for `EGS_RadionuclideSpectrum`. Also allow the user to use the input parameter `nuclide` or `isotope` interchangably.

Add radionuclide alpha scoring options

---

HEN_HOUSE/omega/progs/gui/beamnrc/syncmlce.tcl

Fix nleaf input in SYNCMLCE GUI

---

HEN_HOUSE/doc/src/irs.bib
HEN_HOUSE/doc/src/pirs509a-beamnrc/pirs509a-beamnrc.tex
HEN_HOUSE/doc/src/pirs701-egsnrc/inputs/new_um_app2.tex
HEN_HOUSE/doc/src/pirs794-dosxyznrc/pirs794-dosxyznrc.tex
HEN_HOUSE/omega/progs/beamdp/beamdp.mortran
HEN_HOUSE/scripts/configure.expect

We should fold this in before merging into master for the release.

Small stuff

---

HEN_HOUSE/scripts/egsnrc_fishrc_additions
HEN_HOUSE/scripts/finalize_egs_foruser

Just converted the egsnrc_bashrc_additions script to work with the [fish shell](https://github.com/fish-shell/fish-shell) because I was tired of switching back to bash whenever I wanted to use BEAMnrc :)
Also added the proper detection flag in finalize_egs_foruser.

Add support for fish shell

---

README.md

Update readme to link to reddit page, remove google+ link.

Update readme to link to reddit page

---

HEN_HOUSE/egs++/ausgab_objects/egs_phsp_scoring/egs_phsp_scoring.cpp
HEN_HOUSE/egs++/ausgab_objects/egs_phsp_scoring/egs_phsp_scoring.h
HEN_HOUSE/user_codes/tutor2pp/tutor2pp.cpp
HEN_HOUSE/user_codes/tutor7pp/tutor7pp.cpp

Fix egs++ compiler warnings. This is just for tidyness and doesn't affect any behaviour. Also ran `astyle` on the codes I touched.

Fix a few egs++ compiler warnings

---

HEN_HOUSE/scripts/batch_options.slurm
HEN_HOUSE/scripts/run_user_code_batch

This is a stub to merge in #40, which ended up orphaned (original repo unknown). See discussion in #40. Squased commits in a single one, added "Contributors" to the header. Merging based on approved reviews in #40.

Add slurm support in parallel job submission script

---

HEN_HOUSE/user_codes/g/g.mortran

Check maximum source energy against production threshold UE, UP

---

HEN_HOUSE/user_codes/dosrznrc/dosrznrc.mortran

- Fixes issue #661 using fix offered by @dworogers
- Modified three comment lines that went over 80 characters
**Note:** No calculation tests performed as that has been done by @dworogers

Flag Rayleigh photons as scattered in dosrznrc

---

HEN_HOUSE/egs++/Makefile
HEN_HOUSE/egs++/geometry/egs_lattice/Makefile
HEN_HOUSE/egs++/geometry/egs_lattice/egs_lattice.cpp
HEN_HOUSE/egs++/geometry/egs_lattice/egs_lattice.h
HEN_HOUSE/egs++/geometry/examples/example_egs_lattice.geom

This is an update and rebase stand-in for pull request #561. I was not able to push the update to the original PR branch by @MartinMartinov, hence I created this new pull request to be able to merge into `develop`. Pull request #561 has already been reviewed and approved, so I will not wait for reviews on this one.

Add the egs_lattice library with example geometry input file

---

.gitignore
HEN_HOUSE/doc/src/getting-started/getting-started.tex
HEN_HOUSE/doc/src/pirs794-dosxyznrc/inputs/dosxyznrc.inp
HEN_HOUSE/doc/src/pirs794-dosxyznrc/pirs794-dosxyznrc.tex
HEN_HOUSE/doc/src/pirs898-egs++/egs_chamber.doxy
HEN_HOUSE/doc/src/pirs898-egs++/egs_kerma.doxy
HEN_HOUSE/egs++/geometry/egs_autoenvelope/volcor.h
HEN_HOUSE/egs++/geometry/egs_cylinders/egs_cylinders.h
HEN_HOUSE/egs++/geometry/egs_nd_geometry/egs_nd_geometry.h
HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran
HEN_HOUSE/user_codes/egs_cbct/example_w5br.egsinp

This pull request is meant to accumulate small changes (typos, indentation, white space, comments, etc.) that has little or no impact on the code proper. It should be merged into develop periodically, ideally before a merge into master. After a merge, the branch should be kept alive to accumulate small stuff for the next round. Reviews should only be requested before the merge into develop.

Sweat the small stuff

---

HEN_HOUSE/egs++/egs_advanced_application.cpp
HEN_HOUSE/egs++/egs_object_factory.cpp

I compiled `egs++` and `tutor7pp` with `g++ -fsanitize=address -static-libasan` and ran `tutor7pp -i tracks1.egsinp -p tutor_data.pegs4dat`. There were a few small memory leaks (~1kB) reported, which seem to have been fixed by the changes here. They all appear to be true positives (see comments inline). Address sanitizer is no longer reporting any issues with `tutor7pp`. I also ran `ubsan` with `tutor7pp` but nothing was reported.
<details>
<summary> Full asan log for tutor7pp before PR changes </summary>
```
==4210==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 88 byte(s) in 1 object(s) allocated from:
#0 0x5575f11baa98 in operator new[](unsigned long) (/home/max/projects/EGSnrc/egs_home/bin/linux/tutor7pp+0x1baa98)
#1 0x5575f1260203 in …
```

Fix some memory leaks in egs++ reported by AddressSanitizer

---

HEN_HOUSE/makefiles/beam_makefile
HEN_HOUSE/omega/beamnrc/CMs/MLCE_macros.mortran

Position of comment caused a compilation error.  
Fixes #928.

Fix mlce comment

---

HEN_HOUSE/egs++/geometry/egs_box/egs_box.h

Clarify egs_box example with explicit bounds

---

HEN_HOUSE/omega/beamnrc/beamnrc_user_macros.mortran

Necessary for Lab 4.5, Question 4.5.1, but it's probably a good idea to increase this anyway.

Increase $MXBRSPLIT to 5000.

---

HEN_HOUSE/user_codes/flurznrc/flurznrc_template.egsinp

Fix errors in flurznrc_template.egsinp

---

HEN_HOUSE/user_codes/edknrc/edknrc.make

Fix #1031: Added pegsless source files to edknrc.make

---

HEN_HOUSE/omega/progs/gui/dosxyznrc/load_input2_nrc.tcl

Fix #821: load i_phsp_out when reading dosxyznrc .egsinp file

---

HEN_HOUSE/omega/progs/gui/beamnrc/syncjaws.tcl

Fix (dyn/sync)jaw definition using field dimensions

---

HEN_HOUSE/doc/src/pirs794-dosxyznrc/inputs/dosxyznrc.inp
HEN_HOUSE/doc/src/pirs794-dosxyznrc/pirs794-dosxyznrc.tex
HEN_HOUSE/user_codes/dosxyznrc/dosxyznrc.mortran

Fix #768: documentation for BEAM_SIZE

---

HEN_HOUSE/user_codes/egs_kerma/egs_kerma.cpp

Fixes
====
- Average source energy calculation was assuming a statistical weight
of 1 and lumping all particles together. Now weight is accounted for,
and average energy for photons and charge particles scored separately.
Moreover, average energy of scoring photons is also estimated.
- Typos in differential fluence xmgrace file output
Additions
=========
- Flexible scoring region input spares user from having to enter huge
number of regions one at the time. Here are the different input
schemes:
a) Individual entries using 'scoring regions' input key
Simply enter scoring regions individually
b) Initial and final region pairs using `scoring region ranges`
Expects pairs of initial and final scoring regions
c) Groups of regions using 'scoring start region' and 'scoring stop
region' input keys …

Several improvements and bug fixes for egs kerma

---

HEN_HOUSE/user_codes/egs_cbct/egs_cbct.cpp

Fix egs cbct projection input

---

HEN_HOUSE/egs++/sources/egs_isotropic_source/egs_isotropic_source.cpp
HEN_HOUSE/egs++/sources/egs_isotropic_source/egs_isotropic_source.h

Adds two new options to the isotropic source, to allow for the region selection to be done by material (as well as by region number). Regions are included as part of the source if they match both the region filtering and the medium filtering.
```
medium selection = IncludeSelected # IncludeSelected or ExcludeSelected
selected media = air water # a list of medium names
```

Add isotropic source filtering by medium

---

HEN_HOUSE/egs++/egs_particle_track.cpp

Fix track sorting used for dynamic .ptracks files containing time indices. Usually the original .ptracks file is overwritten by the sorted one, but on Windows file deletion may be blocked. As a workaround for this situation, the sorted .ptracks file is left as a separate file (only when it's not possible to do the deletion).
Side note: anywhere we use `std::remove()` or `std::rename()` may fail on Windows due to restricted permissions, we should be careful about checking that it succeeded.

Fix track sorting for dynamic ptracks on windows
